let msgs = [
		{ id: "f0", text: "Hello", e: ["f1", "fp1", "r"], typing: 0.0 },
		{ id: "f1", text: "Is anybody there?", e: ["u2a", "u2b"] },
		{ id: "u2a", text: "Hello", e: ["f3"] },
		{ id: "u2b", text: "Yeah! What’s up?", e: ["f3"] },
		{ id: "f3", text: "I'm Freddy, a fairy.", e: ["u4a", "u4b"], critical:true },
		{ id: "u4a", text: "Fairies are real?", e: ["f5a"] },
		{ id: "u4b", text: "What's the matter?", e: ["f5b"] },
		{ id: "f5a", text: "Yes, they are! A researcher abandoned us here on this island to see how we develop.", e: ["f5.1a"] },
		{ id: "f5b", text: "There's a researcher here, he is catching all the fairies!", e: ["f6"], typing: 4.0 },
		{ id: "f5.1a", text: "But I think the time has come...", e: ["f5.2a"] },
		{ id: "f5.2a", text: "The researcher is trying to catch us all!", e: ["f6"] },
		{ id: "f6", text: "I'm scared...", e: ["u7a", "u7b"] },
		{ id: "u7a", text: "Oh no! That sounds dangerous...", e: ["f8"] },
		{ id: "u7b", text: "Have you done anything about it yet?", e: ["f8"] },
		{ id: "f8", text: "The only idea I have had so far is to try to reach someone here in the chat. And luckily you answered!", e: ["f9"] },
		{ id: "f9", text: "Will you help me?", e: ["u10a", "u10b"] },
		{ id: "u10a", text: "I don't know how...", e: ["f11"] },
		{ id: "u10b", text: "How can I help you?", e: ["f11"] },
		{ id: "f11", text: "Oh, I almost forgot! Do you see the map?", e: ["u12a", "u12b"] },
		{ id: "u12a", text: "Yes!", e: ["f14"] },
		{ id: "u12b", text: "What map?", e: ["f13"] },
		{ id: "f13", text: "The one behind the chat window. If you click on the little white arrow, you can see it better.", e: ["f14"] },
		{ id: "f14", text: "On the map you can see camera icons. You can click on them and see what the camera is filming.", e: ["f15"] },
		{ id: "f15", text: "Do you see the camera that is blinking? If you click on it, you can see me!", e: ["f16"] }, 
		{ id: "f16", text: "Give it a try!", e: [] }, //special
		{ id: "f17", text: "Click on the small white arrow at the edge of the chat window and you will see the whole island. Click on the blinking camera.", e: [] }, //special
		{ id: "f18", text: "Did you see me?", e: ["u19a", "u19b"] },
		{ id: "u19a", text: "Yes, hi Freddy!", e: ["f23"] },
		{ id: "u19b", text: " No.", e: ["f20"] },
		{ id: "f20", text: "I am on the right side of the picture.", e: ["f21"] },
		{ id: "f21", text: "Why don't you check again?", e: ["u22b"] },
		{ id: "u22b", text: "Okay", e: [] }, //special
		{ id: "f23", text: "If you click on the other camera right next to it, you will also see my hut, I built it myself!", e: ["u24a", "u24b"] },
		{ id: "u24a", text: "Great place! ", e: ["f26"] },
		{ id: "u24b", text: "I thought you had a problem?", e: ["f25"] },
		{ id: "f25", text: "Yes, you're right!", e: ["f26"] },
		{ id: "f26", text: "I could either hide in my hut or fly up into the treetops where the explorer cannot reach me. What do you think?", e: ["u27a", "u27b"] },
		{ id: "u27a", text: "Hut", e: ["f28"] },
		{ id: "u27b", text: "Tree tops", e: ["f28"] },
		{ id: "f28", text: "Okay, if you want to watch, then click on the camera icon again!", e: ["f29"] },
		{ id: "f29", text: "I'll send you a message as soon as I have arrived.", e: [] }, //special
		{ id: "f30", text: "Ehmmm", e: ["f31", "fp2"] },
		{ id: "f31", text: "So the plan didn't quite work out...", e: ["u32a", "u32b"] },
		{ id: "u32a", text: "I saw!", e: ["f34"] },
		{ id: "u32b", text: "What happened?", e: ["f33"] },
		{ id: "f33", text: "I fell. My wings did not carry me.", e: ["f34"] },
		{ id: "f34", text: "I am now sitting next to my hut under a bush, and the researcher does not see me here either.", e: ["u35a", "u35b"] },
		{ id: "u35a", text: "Did you hurt yourself?", e: ["f36a"] },
		{ id: "u35b", text: "Good, so you're safe.", e: ["f36b"] },
		{ id: "f36a", text: "No, it's fine, I'm used to it. Luckily I'm well padded.", e: ["u37a", "u37b"] },
		{ id: "f36b", text: "Yeah, at least I ended up in a safe place.", e: ["u37a", "u37b"] },
		{ id: "u37a", text: "Does that happen to you a lot?", e: ["f38a"] },
		{ id: "u37b", text: "Good.", e: ["f39"] },
		{ id: "f38a", text: "Yes, every time! I think my belly is too big to fly.", e: ["f39"] },
		{ id: "f39", text: "Oh, I see the researcher.", e: ["f40", "r"] },
		{ id: "f40", text: "Hahaha. You know what just happened? A bug landed on the researchers's arm! And the researcher... Hahahahaha I can't… He screamed like a little girl and waved his arms wildly! And he is running around like a scared chicken!", e: ["f41", "m"] },
		{ id: "f41", text: "Ohhh watch out he is coming my way, I hope he doesn't see me!", e: ["f42"], typing: 4.0 },
		{ id: "f42", text: "No", e: ["f43"], typing: 5.0 },
		{ id: "f43", text: "Nooo no no", e: ["f44"] },
		{ id: "f44", text: "This can't be happening!", e: ["u45a", "u45b"] },
		{ id: "u45a", text: "What happened?", e: ["f48"] },
		{ id: "u45b", text: "Haha he's afraid of bugs!", e: ["f46"] },
		{ id: "f46", text: "Yes HAHA but I don't care anymore. Something has just happened.", e: ["u47a", "u47b"] },
		{ id: "u47a", text: "What?", e: ["f48"] },
		{ id: "u47b", text: "Tell me", e: ["f48"] },
		{ id: "f48", text: "The worst thing that could have happened... My hut... He stepped on it! Did you see that?", e: ["u49a", "u49b"] },
		{ id: "u49a", text: "No", e: ["f51"] },
		{ id: "u49b", text: "Yes", e: ["f50"] },
		{ id: "f50", text: "Then you know how terrible it was...", e: ["f51"] },
		{ id: "f51", text: "It's broken.", e: ["f52"] },
		{ id: "f52", text: "My everything...", e: ["f53"] },
		{ id: "f53", text: "Broken.", e: ["u54a", "u54b"] },
		{ id: "u54a", text: "Where is the researcher now?", e: ["f55"] },
		{ id: "u54b", text: "What are the other fairies doing?", e: ["f55"] },
		{ id: "f55", text: "The researcher has captured all the fairies with his net, now he has gone.", e: ["f56"] },
		{ id: "f56", text: "But my hut. It's broken.", e: ["u57a", "u57b"] },
		{ id: "u57a", text: "Why is your hut so important to you?", e: ["f58a"] },
		{ id: "u57b", text: "All of the fairies?", e: ["f58b"] },
		{ id: "f58a", text: "It's all I have. It's not like I can sleep in the trees with the other fairies. I can't fly up there.", e: ["f59"] },
		{ id: "f58b", text: "Yeah, all the fairies that were flying around in the air.", e: ["f60"] },
		{ id: "f59", text: "But now I'm glad I can't fly.", e: ["f60"] },
		{ id: "f60", text: "If I had been up there, I’m sure the researcher would have caught me too!", e: ["u61a", "u61b"] },
		{ id: "u61a", text: "Save the fairies!", e: ["f62a"] },
		{ id: "u61b", text: "Rebuild your hut.", e: ["f62b"] },
		{ id: "f62a", text: "Ehhh why?", e: ["f63a"] },
		{ id: "f62b", text: "Alone? I can't do it.", e: ["f63b"] },
		{ id: "f63a", text: "Now that I finally have some peace?", e: ["f64a"] },
		{ id: "f63b", text: "The other fairies helped me build it. So I wouldn't have to sleep in the trees with them anymore. They wanted to get rid of me as fast as possible.", e: ["f64b"], typing: 5.0 },
		{ id: "f64a", text: "And won't have to hear their gloating laughter every time I'm trying to fly?", e: ["f66"] },
		{ id: "f64b", text: "Even though they were watching me all day anyways. They always found my attempts at flying soooo funny...", e: ["f65"], typing: 4.0 },
		{ id: "f65", text: "Like everything else I do...", e: ["f66"] },
		{ id: "f66", text: "So mean.", e: ["u67a", "u67b"] },
		{ id: "u67a", text: "Now what?", e: ["f68"] },
		{ id: "u67b", text: "What happens next?", e: ["f68"] },
		{ id: "f68", text: "Good question... I can't build this house alone. I'm bored already but I don't want the fairies back. And just walking around and doing nothing is stupid too...", e: ["f69"], typing: 4.0 },
		{ id: "f69", text: "Ohhh I have an idea!", e: ["f70"], typing: 5.0 },
		{ id: "f70", text: "I'll trample on the researcher's house too! Revenge!", e: ["u71a", "u71b"] },
		{ id: "u71a", text: "Great idea!", e: ["f74"] },
		{ id: "u71b", text: "Um... On the roof?", e: ["f72"] },
		{ id: "f72", text: "Um... Yeah? Where else?", e: ["u73a", "u73b"] },
		{ id: "u73a", text: "Good idea. Really. Great.", e: ["f74"] },
		{ id: "u73b", text: "I see...", e: ["f74"] },
		{ id: "f74", text: "Great! Now I just need to know where to go.", e: ["f75"] },
		{ id: "f75", text: "Oh no! I wanted to to look up where to go on the computer in my hut, but of course it's broken now!", e: ["u76a", "u76b"] },
		{ id: "u76a", text: "You have a computer???", e: ["f77a"] },
		{ id: "u76b", text: "How are you texting me?", e: ["f77b"] },
		{ id: "f77a", text: "Yeah, I built it myself! With it I can access the website of the research island.", e: ["f78a"] },
		{ id: "f77b", text: "I hacked myself into the website of the research island. Now I can send messages to you through my smart button. It's like with a smartphone that looks like a normal pants button.", e: ["f78b"], typing: 5.0 },
		{ id: "f78a", text: "Just like with my Smart Button. I'm sending you messages with it right now. It's like a smartphone, only it looks like a button. It's voice-activated, and I'm very proud of that.", e: ["f79"] },
		{ id: "f78b", text: "With voice control, I am particularly proud of that!", e: ["f79"], typing: 5.0 },
		{ id: "f79", text: "You can find the story on my <a href=\"https://instagram.com/freddysreise/\">Instagram</a> and <a href=\"https://www.facebook.com/freddysreise\">Facebook</a> profile. If you want, we can become friends there! ", e: ["u80a", "u80b"], typing: 4.0 },
		{ id: "u80a", text: "You're weird...", e: ["f81"] }, 
		{ id: "u80b", text: "What? Really?", e: ["f81"] },
		{ id: "f81", text: "I have to do something with my time. I have no friends...", e: ["f82"] },
		{ id: "f82", text: "But back to my revenge plan.", e: ["f83"] },
		{ id: "f83", text: "You can access the website and the cameras! That way I don't need my computer. You can tell me what to do.", e: ["u84a", "u84b"], typing: 4.0 },
		{ id: "u84a", text: "How?", e: ["f85"] },
		{ id: "u84b", text: "I will!", e: ["f85"] },
		{ id: "f85", text: "You can click on all of the cameras. So you can see what's happening there right now.", e: ["f86", "m"] },
		{ id: "f86", text: "Do you remember how?", e: ["u87a", "u87b"] },
		{ id: "u87a", text: "Yes", e: ["f88a"] },
		{ id: "u87b", text: "No", e: ["f88b"] },
		{ id: "f88a", text: "Super!", e: ["f89"] },
		{ id: "f88b", text: "There is a map behind the chat window. If you click on the small white arrow, you can see it better. Then you can click on the cameras.", e: ["f89"] },
		{ id: "f89", text: "Have a look if you can find a hint where the researcher went! Where do you want me to go? Up, down or to the right on the map?", e: ["u90a", "u90b", "u90c"], typing: 4.0 },
		{ id: "u90a", text: "Up", e: ["f91", "fp3"] },
		{ id: "u90b", text: "Down", e: ["f94", "fp4"] },
		{ id: "u90c", text: "Right", e: ["f97", "fp5"] },
		{ id: "f91", text: "This is as far as I can go. Do you see me?", e: ["f92"] },
		{ id: "f92", text: "I'm standing in front of a steep mountain, I can't get up...", e: ["f93"] },
		{ id: "f93", text: "Take a close look at the other recordings. Hopefully you will be able to find a clue!", e: ["u90b", "u90c"] },
		{ id: "f94", text: "This is as far as I can go. Do you see me?", e: ["f95"] },
		{ id: "f95", text: "I'm standing on a cliff, I can't get down. And anyway, there's only the sea.", e: ["f96"] },
		{ id: "f96", text: "Take a close look at the other recordings. Hopefully you will be able to find a clue!", e: ["u90a", "u90c"] },
		{ id: "f97", text: "Okay, I'll see what you have found!", e: ["f98"] },
		{ id: "f98", text: "Oh, it's a bit swampy there, I hope the ground holds me...", e: ["u99a", "u99b"] },
		{ id: "u99a", text: "Stay on the edge", e: ["f100"] },
		{ id: "u99b", text: "Take small steps", e: ["f100"] },
		{ id: "f100", text: "Okay... I'll be very careful.", e: ["f101"] },
		{ id: "f101", text: "Unfortunately, I can't see my feet either, my stomach's in the way...", e: ["f102"] },
		{ id: "f102", text: "Oh no!!!!!!", e: ["u103a", "u103b", "m"] },
		{ id: "u103a", text: "What?", e: ["f105"] },
		{ id: "u103b", text: "Are you stuck?", e: ["f104"] },
		{ id: "f104", text: "Yes!", e: ["f105"] },
		{ id: "f105", text: "I got stuck.", e: ["f106"] },
		{ id: "f106", text: "What should I do?", e: ["u107a", "u107b"] },
		{ id: "u107a", text: "Move your arms", e: ["f108"] },
		{ id: "u107b", text: "Don't move!", e: ["f109"] },
		{ id: "f108", text: "Oh no, I'm sinking faster and faster!", e: ["f109"] },
		{ id: "f109", text: "Now what?", e: ["u110a", "u110b"] },
		{ id: "u110a", text: "Call for help!", e: ["f113"] },
		{ id: "u110b", text: "I'll check the cameras!", e: ["f111"] },
		{ id: "f111", text: "Super thanks, that's a good idea!", e: [] },
		{ id: "u112", text: "There are bees. Call for help!", e: ["f113"] },
		{ id: "f113", text: "No! I don't want anyone to make fun of the fat fairy stuck in the swamp.", e: ["f114"] },
		{ id: "f114", text: "And in case it's not clear, by the fat fairy I mean me.", e: ["u115a" ,"u115b"] },
		{ id: "u115a", text: "Oh Freddy…", e: ["f116"] }, 
		{ id: "u115b", text: "I want to help!", e: ["f116"] }, 
		{ id: "f116", text: "Please look if you can see anything in any surveillance video that might help me.", e: ["u117"] },
		{ id: "u117", text: "Okay", e: [""] }, //special
		{ id: "u118", text: "There's a bee with a cane for the blind.", e: ["f119"] },
		{ id: "f119", text: "A blind bee?", e: ["f120"] },
		{ id: "f120", text: "Hm okay, I will call it. It won't laugh at me if it can't see me.", e: ["f121"] },
		{ id: "f121", text: "Wait, I'll text you later.", e: ["m"], critical:true }, //special
		{ id: "f122", text: "Okay, I did it. I called the bee.", e: ["f123"], typing: 4.0 },
		{ id: "f123", text: "The bee's name is Benny.", e: ["f124"] },
		{ id: "f124", text: "He helped me, I'm free again!", e: ["u125a", "u125b"] },
		{ id: "u125a", text: "Without seeing?", e: ["f126"] },
		{ id: "u125b", text: "Great!", e: ["f127"] },
		{ id: "f126", text: "I told him exactly what to do.", e: ["f127"] },
		{ id: "f127", text: "I told him about you because he thought it was weird that I was talking to myself.", e: ["f128"], typing: 4.0 },
		{ id: "f128", text: "Because of the voice input of my smart button.", e: ["f129"], typing: 3.0 },
		{ id: "f129", text: "And I told him about my revenge plan.", e: ["f130"], typing: 3.0 },
		{ id: "f130", text: "Benny says he heard the explorer with the fairies. He knows where the explorer lives.", e: ["f131"], typing: 3.0 },
		{ id: "f131", text: "Should I ask him to show us the way?", e: ["u132a", "u132b"] },
		{ id: "u132a", text: "I'm sure he has better things to do.", e: ["f133"] },
		{ id: "u132b", text: "Yes!", e: ["f134"] },
		{ id: "f133", text: "Oh, he heard me ask you. So voice control has its drawbacks.", e: ["f134"] },
		{ id: "f134", text: "He says he'd like to come along! Great!", e: ["u135a", "u135b"] },
		{ id: "u135a", text: "Let's go!", e: ["f136a"] },
		{ id: "u135b", text: "That's nice of him.", e: ["f136b"] },
		{ id: "f136a", text: "All right, all right, we're on our way!", e: ["f137"] },
		{ id: "f136b", text: "Yes, I think so too!", e: ["f137"] },
		{ id: "f137", text: "I think we'll get along fine.", e: ["f138"] },
		{ id: "f138", text: "Benny says that he has never have been so far away from home without the other bees.", e: ["u139a", "u139b"], typing: 4.0 },
		{ id: "u139a", text: "How does he know the way?", e: ["f140"] },
		{ id: "u139b", text: "Okay.", e: ["f141"] },
		{ id: "f140", text: "He can smell the flowers on the way. Each one smells different. Unfortunately, I can't smell as well as he can.", e: ["f141"] },
		{ id: "f141", text: "Oh I see a rooftop in the distance. I can't wait to trample on it!", e: ["f142"], typing: 4.0 },
		{ id: "f142", text: "Muahahahaha", e: ["f143"] },
		{ id: "f143", text: "I hope you just read that in your most evil voice. That was my evil laugh.", e: ["f144"], typing: 4.0 },
		{ id: "f144", text: "Benny says we're almost there.", e: ["u145a", "u145b"] },
		{ id: "u145a", text: "Can you climb that high?", e: ["f146"] },
		{ id: "u145b", text: "What will you do after the revenge?", e: ["f146"] },
		{ id: "f146", text: "Wait.", e: ["f147", "m"] },
		{ id: "f147", text: "Benny, I can't get through there, there's a cliff! There's a cliff! I didn't know that! I always fly through here normally. Benny!", e: ["u148a",  "u148b"] },
		{ id: "u148a", text: "Hello, Freddy?", e: ["f149"] },
		{ id: "u148b", text: "What's the matter?", e: ["f149"] },
		{ id: "f149", text: "Oh, the voice input was still switched on. It sent you Benny and my conversation. Oops.", e: ["f150"] },
		{ id: "f150", text: "Something very bad happened! Can you see me on the camera? I see there's one hanging there.", e: ["u151a", "u151b", "fp6"] },
		{ id: "u151a", text: "Come on, tell me.", e: ["f152"] },
		{ id: "u151b", text: "Okay, I'll check.", e: [""] }, //special
		{ id: "f152", text: "There's a ditch between us and the house.", e: ["f153"] },
		{ id: "f153", text: "I can't get through there. Benny can fly. It's no problem for him. But I don't want to try it and fall down there... In the forest it's not that bad, but down here there are only stones and a river!", e: ["f154"], typing: 5.0 },
		{ id: "f154", text: "Waaaaay down…", e: ["u155a", "u155b"], typing: 4.0 },
		{ id: "u155a", text: "Can Benny fly you over?", e: ["f156a"] },
		{ id: "u155b", text: "Okay. Go home.", e: ["f156b"] },
		{ id: "f156a", text: "Did you see how small he is? And how big I am?", e: ["f157a"] },
		{ id: "f156b", text: "And what about my revenge plan?", e: ["f157b"] },
		{ id: "f157a", text: "No, I'm too heavy for Benny. I don't want to risk it…", e: ["f158"] },
		{ id: "f157b", text: "I'm not giving up. ", e: ["f158"] },
		{ id: "f158", text: "We need another solution. There are branches lying around and we can use the grass for something.", e: ["f159"], typing: 4.0 },
		{ id: "f159", text: "What do you think?", e: ["u160a", "u160b"] },
		{ id: "u160a", text: "Use the grass as string.", e: ["f161a"] },
		{ id: "u160b", text: "Use a branch like a bridge.", e: ["f161b"] },
		{ id: "f161a", text: "That's a great idea!", e: ["f162"] },
		{ id: "f161b", text: "Did you see how short those sticks are? They are too short and do not reach the other side.", e: ["f162"] },
		{ id: "f162", text: "I could either tie the branches together so that I have a long pole and then balance on it to the other side. That would be very quick and easy to build.", e: ["f163"], typing: 5.0 },
		{ id: "f163", text: "Or I build a suspension bridge. That would take a lot longer. But it would be more stable and less dangerous.", e: ["f164"], typing: 4.0 },
		{ id: "f164", text: "Please decide for me.", e: ["u165a", "u165b"] },
		{ id: "u165a", text: "Pole", e: ["f166"] },
		{ id: "u165b", text: "Suspension bridge", e: ["f187"] },
		//Stab:
		{ id: "f166", text: "Okay, then I'll tie the branches together with grass.", e: ["f167"] },
		{ id: "f167", text: "I hope this holds with only one blade of grass as a string...", e: ["u168a", "u168b"], typing: 3.0  },
		{ id: "u168a", text: "Take several.", e: ["f169a"] },
		{ id: "u168b", text: "It will be all right.", e: ["f169b"] },
		{ id: "f169a", text: "That's a good idea. I think it will be much more stable this way.", e: ["f170"] },
		{ id: "f169b", text: "Okay, I hope you're right.", e: ["f170"] },
		{ id: "f170", text: "I think this should do it.", e: ["f171"], typing: 3.0  },
		{ id: "f171", text: "I'll ask Benny to fly beside me, just in case.", e: ["f172"], typing: 4.0  },
		{ id: "f172", text: "Ohh and it's wobbly, I'd rather hold on to his hand.", e: ["u173a", "u173b"], typing: 4.0  },
		{ id: "u173a", text: "Haha you're scared!", e: ["f174a"] },
		{ id: "u173b", text: "Safety first!", e: ["f174b"] },
		{ id: "f174a", text: "Remember, if I fall down it's your fault, you told me to tie the sticks together!", e: ["f175"] },
		{ id: "f174b", text: "Yeah, I agree.", e: ["f175"] },
		{ id: "f175", text: "I have a little problem. My smart button I use to send you messages is too heavy, it throws me off balance.", e: ["f176"], typing: 4.0 },
		{ id: "f176", text: "I'm afraid I have to leave it here.", e: ["u177a", "u177b"], typing: 3.0 },
		{ id: "u177a", text: "Good luck.", e: ["f178"] },
		{ id: "u177b", text: "No, Freddy, don't leave me!", e: ["f178"] },
		{ id: "f178", text: "You can still watch me on the cameras.", e: ["f179"] },
		{ id: "f179", text: "Well, I'm off. Click on the camera and you'll see me cross over.", e: [""], critical:true }, //special
		{ id: "f180", text: "Here I am again. That was a brief separation.", e: ["u181a", "u181b"] },
		{ id: "u181a", text: "Are you okay?", e: ["f182a"] },
		{ id: "u181b", text: "What happened?", e: ["f182b"] },
		{ id: "f182a", text: "Yes, Benny saved me.", e: ["f183"] },
		{ id: "f182b", text: "I fell off the pole, my balance is not so good, unfortunately. Luckily Benny caught me.", e: ["f183"] },
		{ id: "f183", text: "I've been lucky again!", e: ["u184a", "u184b"] },
		{ id: "u184a", text: "Good!", e: ["f185"] },
		{ id: "u184b", text: "Now what?", e: ["f185"] },
		{ id: "f185", text: "I have let you decide and it almost killed me. Now I decide. I'll build the suspension bridge. It'll take longer, but at least I won't fall down again!", e: ["u186a", "u186b"] },
		{ id: "u186a", text: "Whatever you say.", e: ["f187"] },
		{ id: "u186b", text: "Good idea!", e: ["f187"] },
		//Hängebrücke:
		{ id: "f187", text: "Okay, let's build a suspension bridge. We can do it!", e: ["f188"] }, 
		{ id: "f188", text: "I'll ask Benny if he can help me.", e: ["u189a", "u189b"], typing: 3.0 },
		{ id: "u189a", text: "You know how to do that?", e: ["f190"] },
		{ id: "u189b", text: "Good.", e: ["f192"] },
		{ id: "f190", text: "Well, I have built a suspension bridge before. You know, when I couldn't fly anymore, I was still living up in the tree with the other fairies. And to get there, I built bridges between the trees.", e: ["f191"], typing: 4.0  },
		{ id: "f191", text: "You can find the story on my social media channels. It's on <a href=\"https://instagram.com/freddysreise/\">Instagram</a> and <a href=\"https://www.facebook.com/freddysreise\">Facebook</a> if you want to have a look!", e: ["f192"], typing: 5.0  },
		{ id: "f192", text: "I'm so glad Benny came with me. I wonder what happened to the fairies.", e: ["u193a", "u193b"], typing: 4.0 },
		{ id: "u193a", text: "Benny's great!", e: ["f198"] },
		{ id: "u193b", text: "Poor fairies.", e: ["f194"] },
		{ id: "f194", text: "They have always been so mean to me but now I feel a little sorry for them...", e: ["u195a", "u195b"] },
		{ id: "u195a", text: "Save them!", e: ["f196a"] },
		{ id: "u195b", text: "They deserve it.", e: ["f196b"] },
		{ id: "f196a", text: "Hmm, I don't know... So they can laugh at me again? No, I guess not.", e: ["f197"] },
		{ id: "f196b", text: "You're right.", e: ["f197"] },
		{ id: "f197", text: "Fortunately, Benny's different.", e: ["f198"], typing: 3.0  },
		{ id: "f198", text: "I've never had a friend like him... I think I want to tell him about how the fairies treated me.", e: ["u199a", "u199b"] },
		{ id: "u199a", text: "Yes, do that!", e: ["f200a"] },
		{ id: "u199b", text: "Finish the bridge first.", e: ["f200b"] },
		{ id: "f200a", text: "Benny just suggested that we could go for a swim in that puddle over there. I like that, so I can tell him my story.", e: ["f204"] },
		{ id: "f200b", text: "Okay if you say so. But before Benny flies to the other side, we'll take a break.", e: ["f201"] },
		{ id: "f201", text: "It's sooo hot.", e: ["f202"], typing: 3.0  },
		{ id: "f202", text: "I see a puddle. We can bathe in it!", e: ["f203"], typing: 3.0  },
		{ id: "f203", text: "Benny thinks it's a good idea.", e: ["f204"], typing: 3.0  },
		{ id: "f204", text: "You know what? I can even take my pants off without any problem so they don't get wet. Benny can't see me anyway!", e: ["u205a", "u205b"], typing: 4.0 },
		{ id: "u205a", text: "How convenient!", e: ["f206"] },
		{ id: "u205b", text: "Great!", e: ["f206"] },
		{ id: "f206", text: "I agree!", e: ["f207"] },
		{ id: "f207", text: "Okay, I'm sitting in the puddle, I've got my smart button next to me so I can keep you updated on the conversation.", e: ["f208"], typing: 4.0 },
		{ id: "f208", text: "Well, I'll tell Benny that the fairies always laugh at me.", e: ["f209"], typing: 4.0 },
		{ id: "f209", text: "Benny asks why.", e: ["f210"], typing: 4.0 },
		{ id: "f210", text: "What should I say?", e: ["u211a", "u211b"], typing: 4.0 },
		{ id: "u211a", text: "Because of your big belly.", e: ["f212"] },
		{ id: "u211b", text: "Because of your potato nose.", e: ["f212"] },
		{ id: "f212", text: "Okay, I said it.", e: ["f213"] },
		{ id: "f213", text: "Oh no!!!!!!", e: ["f214"], typing: 4.0 },
		{ id: "f214", text: "No no no no no!", e: ["f215"], typing: 4.0 },
		{ id: "f215", text: "A bird stole my pants!", e: ["f216"], typing: 3.0 },
		{ id: "f216", text: "And I couldn't catch it...", e: ["f217"] },
		{ id: "f217", text: "Now I have to end my revenge trip naked!", e: ["u218a", "u218b", "m"], typing: 3.0 },
		{ id: "u218a", text: "Hahahahaha", e: ["f219a"] },
		{ id: "u218b", text: "Oh no!", e: ["f219b"] },
		{ id: "f219a", text: "Benny laughs at me too!", e: ["f220"] },
		{ id: "f219b", text: "You know what Bennys reaction to my story is? He is laughing at me!", e: ["f220"] },
		{ id: "f220", text: "How dare he! I thought he was different. I finally found someone I trusted and now he just laughs at me. I thought he didn't care how I looked, but he does! He just didn't know it, and now that he knows, he's laughing at me too.", e: ["f221"], typing: 5.0 },
		{ id: "f221", text: "They're all the same!", e: ["f222"], typing: 4.0 },
		{ id: "f222", text: "I want him to go away, I don't need friends like that!", e: ["u223a", "u223b"], typing: 3.0 },
		{ id: "u223a", text: "Wait!", e: ["f224"] },
		{ id: "u223b", text: "Don't do that!", e: ["f224"] },
		{ id: "f224", text: "What?", e: ["f225"] },
		{ id: "f225", text: "So, now he's gone. Traitor!", e: ["u226a", "u226b"] },
		{ id: "u226a", text: "No, Freddy!", e: ["f227"] },
		{ id: "u226b", text: "Why?", e: ["f227"] },
		{ id: "f227", text: "He laughed at me, he deserved it!", e: ["u228a", "u228b"] },
		{ id: "u228a", text: "He's your friend!", e: ["f229"] },
		{ id: "u228b", text: "He wasn't laughing at you!", e: ["f230"] },
		{ id: "f229", text: "But he laughed!", e: ["f230"] },
		{ id: "f230", text: "What else would he have laughed about?", e: ["u231a", "u231b"] },
		{ id: "u231a", text: "Jumping on the roof naked.", e: ["f232"] },
		{ id: "u231b", text: "Nakedness is funny. ", e: ["f232"] },
		{ id: "f232", text: "Haha", e: ["f233"] },
		{ id: "f233", text: "Well, yes, but what does that have to do with anything?", e: ["f234"], typing: 3.0 },
		{ id: "f234", text: "Ahhhhh okay", e: ["f235"], typing: 4.0 },
		{ id: "f235", text: "I see what you mean.", e: ["f236"], typing: 3.0 },
		{ id: "f236", text: "He wasn't laughing at me at all, his laughter had nothing to do with my story!", e: ["u237a", "u237b"], typing: 4.0 },
		{ id: "u237a", text: "Look for Benny", e: ["f238a"] },
		{ id: "u237b", text: "Find your pants first", e: ["f238b"] },
		{ id: "f238a", text: "Okay, Benny flew away towards the mountains. Can you see him in a video?", e: ["u240a"] },
		{ id: "f238b", text: "Okay, the birds have flown away towards the mountains. Do you see them or my pants in a video?", e: ["u240a", "u240b"] },
		{ id: "u240a", text: "No", e: ["f241"] },
		{ id: "u240b", text: "There are no cameras there.", e: ["f241"] },
		{ id: "f241", text: "Hmmmm…", e: ["f242"] },
		{ id: "f242", text: "What should I do now? I am naked, alone, and because the bridge is not yet fixed on the other side, I cannot continue my revenge plan...", e: ["u243a", "u243b"], typing: 4.0 },
		{ id: "u243a", text: "Wait, he'll be back.", e: ["f244a"] },
		{ id: "u243b", text: "Call Benny.", e: ["f244b"] },
		{ id: "f244a", text: "I hope so. I don't know what I'm gonna do without him...", e: ["f247"] },
		{ id: "f244b", text: "Okay, I'm shouting as loud as I can.", e: ["f245"] },
		{ id: "f245", text: "Nothing. I can hear my own echo, but I don't see Benny.", e: ["f246"], typing: 4.0 },
		{ id: "f246", text: "I hope he comes back. I don't know what I'm gonna do without him...", e: ["f247"], typing: 4.0 },
		{ id: "f247", text: "I'll wait in the puddle. At least no one will see me naked like this.", e: ["u248a", "u248b"], typing: 4.0 },
		{ id: "u248a", text: "What will you do if Benny doesn't come back?", e: ["f249"] },
		{ id: "u248b", text: "Good idea.", e: ["f252"] },
		{ id: "f249", text: "Then I'll have to go back home.", e: ["u250a", "u250b"] },
		{ id: "u250a", text: "Okay", e: ["f252"] },
		{ id: "u250b", text: "Whithout a house?", e: ["f251"] },
		{ id: "f251", text: "Right, I can't rebuild it by myself...", e: ["f252"] },
		{ id: "f252", text: "Something's coming towards me.", e: ["f253"] },
		{ id: "f253", text: "What's that? It almost looks like a big green balloon...", e: ["f254"], typing: 4.0 },
		{ id: "f254", text: "With stripes on it.", e: ["f255"] },
		{ id: "f255", text: "Oh, you know what? These are my pants!", e: ["u256a", "u256b"], typing: 4.0 },
		{ id: "u256a", text: "Flying pants?", e: ["f257"] },
		{ id: "u256b", text: "Huh?", e: ["f257"] },
		{ id: "f257", text: "Not just my pants! Benny!!!", e: ["f258", "m"] },
		{ id: "f258", text: "Benny's returning my pants!", e: ["u259a", "u259b"] },
		{ id: "u259a", text: "How great!", e: ["f260a"] },
		{ id: "u259b", text: "Apologize!", e: ["f260b"] },
		{ id: "f260a", text: "Yes!", e: ["f261a"] },
		{ id: "f260b", text: "Okay, I told him that I'm sorry.", e: ["f261b"] },
		{ id: "f261a", text: "He has just given me my pants.", e: ["u262a", "u262b"], typing: 4.0 },
		{ id: "f261b", text: "He forgives me!", e: ["f263"], typing: 4.0 },
		{ id: "u262a", text: "What does he say?", e: ["f265"] },
		{ id: "u262b", text: "Apologize!", e: ["f264"] },
		{ id: "f263", text: "Everything's gonna be okay now!", e: ["f265"], typing: 3.0 },
		{ id: "f264", text: "Okay, I will.", e: ["f265"] },
		{ id: "f265", text: "He says it's okay. He knows it's not easy being different.", e: ["f266"], typing: 4.0 },
		{ id: "f266", text: "It never mattered to Benny what I look like. He doesn't care how big or thin I am. He says it's not our looks that make us who we are. What we have inside is more important.", e: ["u267a", "u267b"], typing: 5.0 },
		{ id: "u267a", text: "Beautiful!", e: ["f268a"] },
		{ id: "u267b", text: "Our organs?", e: ["f268b"] },
		{ id: "f268a", text: "Yes, i think so too.", e: ["f269"] },
		{ id: "f268b", text: "No, he means our personality.", e: ["f269"] },
		{ id: "f269", text: "I'm so glad we're friends again!", e: ["u270a", "u270b"] },
		{ id: "u270a", text: "Me too!", e: ["f272"] },
		{ id: "u270b", text: "Have you put your pants back on?", e: ["f271"] },
		{ id: "f271", text: "Yes, I did.", e: ["f272"] },
		{ id: "f272", text: "Okay, back to the plan. Benny has now flown over to the other side of the ditch and is tying up the bridge.", e: ["f273"], typing: 3.0 },
		{ id: "f273", text: "I hope the bridge holds. Take a look at the camera so you'll know if I made it!", e: ["u274a", "u274b"], typing: 4.0 },
		{ id: "u274a", text: "I will!", e: ["f275a"] },
		{ id: "u274b", text: "I don't feel like it.", e: ["f275b"] },
		{ id: "f275a", text: "Great! I'll send you a message when I'm on the other side.", e: [""] }, //special
		{ id: "f275b", text: "Okay. I'll send you a message when I'm on the other side.", e: [] }, //special
		//Haus
		{ id: "f276", text: "Great, I'm on the other side! We are now standing in front of the researcher's house.", e: ["f277", "m", "fp7"], typing: 4.0 }, //ab hier forscher ambi
		{ id: "f277", text: "Shall we walk around it first and see if we are alone or climb up immediately?", e: ["u278a", "u278b"], typing: 4.0 },
		{ id: "u278a", text: "Walk around the house", e: ["f279a"] },
		{ id: "u278b", text: "Climb up", e: ["f279b"] },
		{ id: "f279a", text: "Maybe it's better if we know if we're alone.", e: ["f280"] },
		{ id: "f279b", text: "Let's go!", e: ["f284"] },
		{ id: "f280", text: "There's a big front door.", e: ["u281a", "u281b"], typing: 3.0 },
		{ id: "u281a", text: "Do you see anything?", e: ["f282a"] },
		{ id: "u281b", text: "Open it.", e: ["f282b"] },
		{ id: "f282a", text: "There are two muddy shoes in front of the door.", e: ["f283"] },
		{ id: "f282b", text: "That doesn’t work, it’s too heavy", e: ["f283"] },
		{ id: "f283", text: "All right, let's climb up.", e: ["f284"], typing: 4.0 },
		{ id: "f284", text: "It's difficult...", e: ["f285"], typing: 3.0 },
		{ id: "f285", text: "Should I ask Benny to help me?", e: ["u286a", "u286b"], typing: 3.0 },
		{ id: "u286a", text: "Yes", e: ["f287a"] },
		{ id: "u286b", text: "You can do it alone!", e: ["f287b"] },
		{ id: "f287a", text: "Good, it's easier that way.", e: ["f288"] },
		{ id: "f287b", text: "You're right, I am an independent fairy. I can do this!", e: ["f288"] },
		{ id: "f288", text: "Whew, that was exhausting.", e: ["f289"], typing: 3.0 },
		{ id: "f289", text: "Oh, I see another camera, you can watch me again.", e: ["f290"], typing: 4.0 },
		{ id: "f290", text: "I am looking through the research lab window. And there are the fairies!", e: ["u291a", "u291b"], typing: 4.0 },
		{ id: "u291a", text: "Where?", e: ["f292"] },
		{ id: "u291b", text: "I can see them!", e: ["f293"] },
		{ id: "f292", text: "You can see them through the camera next to the house. They are in a cage and they look very unhappy...", e: ["f293"] },
		{ id: "f293", text: "Now I feel even worse. Should I free them or take revenge on the explorer?", e: ["u294a", "u294b"] },
		{ id: "u294a", text: "Help", e: ["f295"] },
		{ id: "u294b", text: "Revenge", e: ["f297"] },
		{ id: "f295", text: "And just forget about my revenge plan?", e: ["u296a", "u296b"] },
		{ id: "u296a", text: "Yes!", e: ["f304"] },
		{ id: "u296b", text: "No!", e: ["f297"] },
		{ id: "f297", text: "Okay, I'll climb up on the roof.", e: ["f298"] },
		{ id: "f298", text: "Here we go!", e: ["f299"], typing: 3.0 },
		{ id: "f299", text: "Muahahaha! Tit for tat! Serves you right!", e: ["f299.5"], typing: 4.0 },
		{ id: "f299.5", text: "Why can't I enjoy this as much as I thought I would?", e: ["u300a", "u300b"], typing: 4.0 },
		{ id: "u300a", text: "Stupid idea", e: ["f301"] },
		{ id: "u300b", text: "That's long enough.", e: ["f301"] },
		{ id: "f301", text: "I think I know what's going on... I feel bad for the fairies. When I was alone at the ditch, Benny came to help me.", e: ["f302"] },
		{ id: "f302", text: "They need someone like that!", e: ["u303a", "u303b"], typing: 4.0 },
		{ id: "u303a", text: "Be their hero!", e: ["f304"] },
		{ id: "u303b", text: "If you say so...", e: ["f304"] },
		{ id: "f304", text: "Okay, I'll save them! But how?", e: ["u305a", "u305b"] },
		{ id: "u305a", text: "Look at the lab.", e: ["f305a"] },
		{ id: "u305b", text: "Just go.", e: ["f305b"] },
		{ id: "f305a", text: "Good decision! Luckily I checked, because the researcher is here!", e: ["f306"] },
		{ id: "f305b", text: "They say there are no stupid ideas but this one just almost cost me my life! Benny was just able to hold me back, the researcher is in there!", e: ["f306"] },
		{ id: "f306", text: "I can't let him catch me! I don't want to end up in a cage with the other fairies!", e: ["u307a", "u307b"], typing: 5.0 },
		{ id: "u307a", text: "Then go home.", e: ["f308"] },
		{ id: "u307b", text: "Do you have a plan?", e: ["f314"] },
		{ id: "f308", text: "You want me to give up?", e: ["f309"] },
		{ id: "f309", text: "Certainly not. I'll manage somehow. But how?", e: ["u310a", "u310b"], typing: 3.0 },
		{ id: "u310a", text: "Benny can fly.", e: ["f311a"] },
		{ id: "u310b", text: "You go.", e: ["f311b"] },
		{ id: "f311a", text: "But he can't see anything, how should he get to the cage without being caught?", e: ["u312a", "u312b"] },
		{ id: "f311b", text: "Yeah, I think it is me who needs to do that.", e: ["f314"] },
		{ id: "u312a", text: "He is a bee.", e: ["f313"] },
		{ id: "u312b", text: "Then you go.", e: ["f314"] },
		{ id: "f313", text: "Yes, but people don't like bees flying around in their rooms either. I think I have to go myself.", e: ["f314"] },
		{ id: "f314", text: "Oh, and you know what just occurred to me? When the researcher was with us at the fairy village, he got scared of a bug. Maybe we can do something with a bug?", e: ["u315a", "u315b"], typing: 5.0 },
		{ id: "u315a", text: "Do you see one?", e: ["f316a"] },
		{ id: "u315b", text: "You look like a bug.", e: ["f316b"] },
		{ id: "f316a", text: "No", e: ["f320a"] },
		{ id: "f316b", text: "Uhhhm thanks?", e: ["u317a", "u317b"] },
		{ id: "u317a", text: "He will probably think you are one.", e: ["f318a"] },
		{ id: "u317b", text: "I'm sorry.", e: ["f318b"] },
		{ id: "f318a", text: "Ohhh you're right, this could work!", e: ["u319a", "u319b"] },
		{ id: "f318b", text: "Hm okay. There's a rock. Should I throw it and hope it distracts the him?", e: ["u319c", "u319d"] },
		{ id: "u319a", text: "No", e: ["f320a"] },
		{ id: "u319b", text: "Yes", e: ["f340"] },
		{ id: "u319c", text: "Yes", e: ["f325"] },
		{ id: "u319d", text: "No", e: ["f320b"] },
		{ id: "f320a", text: "There's a stone here. Maybe it can help me.", e: ["u321a", "u321b"] },
		{ id: "f320b", text: "I'll just have to jump on him myself...", e: ["f340"] },
		{ id: "u321a", text: "Good idea!", e: ["f322a"] },
		{ id: "u321b", text: "I think not.", e: ["f322b"] },
		{ id: "f322a", text: "Should I throw it?", e: ["u323a", "u323b"] },
		{ id: "f322b", text: "Then what? Should I jump on him myself?", e: ["u323c", "u323d"] },
		{ id: "u323a", text: "Yes", e: ["f325"] },
		{ id: "u323b", text: "No", e: ["f324"] },
		{ id: "u323c", text: "Yes", e: ["f340"] },
		{ id: "u323d", text: "No", e: ["f325"] },
		{ id: "f324", text: "I'll just have to jump on him myself...", e: ["f340"] },
		//Stein:
		{ id: "f325", text: "Okay, I will throw the stone to the other side of the research station, and while the researcher is distracted, I will run to the cage and free the fairies.", e: ["u326a", "u326b"], typing: 3.0 },
		{ id: "u326a", text: "Good idea", e: ["f328"] },
		{ id: "u326b", text: "Can you throw that far?", e: ["f327"] },
		{ id: "f327", text: "I don't know, I guess I'll have to try.", e: ["f328"] },
		{ id: "f328", text: "Okay, I'll throw it. And once i’ve thrown it, I’ll go inside and run to the fairies.", e: ["f329"], typing: 4.0 },
		{ id: "f329", text: "Don't forget you can also watch this in the video.", e: ["f330"], typing: 3.0 },
		{ id: "f330", text: "I'll send you a message when I get back.", e: ["u331a", "u331b"], typing: 3.0 },
		{ id: "u331a", text: "Okay", e: [""] }, //special
		{ id: "u331b", text: "Good luck!", e: [""] },//special
		{ id: "f332", text: "Now I just got lucky again!", e: ["u333a", "u333b"] },
		{ id: "u333a", text: "Did you free them?", e: ["f334"] },
		{ id: "u333b", text: "What happened?", e: ["f335"] },
		{ id: "f334", text: "No, I didn't get that far.", e: ["f335"] },
		{ id: "f335", text: "I was able to throw the stone to the other side of the room, but the researcher just turned around for one second and then just kept working.", e: ["f336"], typing: 4.0 },
		{ id: "f336", text: "I could barely slip back outside before he spotted me...", e: ["u337a", "u337b"], typing: 4.0 },
		{ id: "u337a", text: "Now what?", e: ["f339"] },
		{ id: "u337b", text: "Go home", e: ["f338"] },
		{ id: "f338", text: "No! I won't give up! Never!", e: ["f339"] },
		{ id: "f339", text: "I'll just have to jump on him myself.", e: ["f340"] },
		//Käfer
		{ id: "f340", text: "I think this idea is the only one that will work.", e: ["f341"], typing: 4.0 },
		{ id: "f341", text: "And I do look a bit like a big bug. Let's just hope the researcher won't look too closely...", e: ["u342a", "u342b"], typing: 4.5 },
		{ id: "u342a", text: "It will be all right.", e: ["f343.5"] },
		{ id: "u342b", text: "Can you jump that far?", e: ["f343"] },
		{ id: "f343", text: "I think so. The researcher is working right next to the window.", e: ["f343.5"] },
		{ id: "f343.5", text: "I will jump on his arm and crawl on it like the bug in our forest.", e: ["u344a", "u344b"], typing: 3.0 },
		{ id: "u344a", text: "Okay", e: ["f346"] },
		{ id: "u344b", text: "How will you get to the cage?", e: ["f345"] },
		{ id: "f345", text: "I don't know that yet either. I'll just improvise.", e: ["f346"] },
		{ id: "f346", text: "I can't send you any more messages once I get back to the lab, I need to get this done quickly. Do you want me to give Benny my smart button so he can tell you what he hears?", e: ["u347a", "u347b"], typing: 4.0 },
		{ id: "u347a", text: "Yes", e: ["f348a"] },
		{ id: "u347b", text: "No", e: ["f348b"] },
		{ id: "f348a", text: "Okay, I'll give it to him. I'll hear you later!", e: [""] }, //special
		{ id: "f348b", text: "Okay, if you want to know what's happening, you will have to look at the video. I don't think you're able to look inside the lab, but at least you'll see what's going on outside.", e: ["f349"] },
		{ id: "f349", text: "Okay, I'm going!", e: ["u351a", "u352b"], typing: 4.0 },
		{ id: "f350", text: "Hello, it's Benny!", e: ["u353a", "u353b"] },
		{ id: "u351a", text: "Good Luck!", e: [""] }, //special
		{ id: "u352b", text: "Read you later!", e: [""] }, //special
		{ id: "u353a", text: "Hi, Benny!", e: ["f355"] },
		{ id: "u353b", text: "How can you text me? Aren't you blind?", e: ["f354"] },
		{ id: "f354", text: "The button works by voice input. I can speak normally and the button records it and sends you the message as a text. And your messages are also read to me.", e: ["f355"] },
		{ id: "f355", text: "Okay, Freddy jumped.", e: ["f356", "r"], typing: 4.0 },
		{ id: "f356", text: "I think he reached the researcher! I hear him shrieking!", e: ["f357"], typing: 3.0 },
		{ id: "f357", text: "Now I hear stomping. And a metallic doiiiing. I wonder what that was.", e: ["f358"], typing: 2.0 },
		{ id: "f358", text: "The steps of the researcher become quieter, I think he has left the room.", e: ["u359a", "u359b"] },
		{ id: "u359a", text: "And Freddy?", e: ["f360"] },
		{ id: "u359b", text: "What do you hear now?", e: ["f360"] },
		{ id: "f360", text: "Shh! I can't hear! I hear the whisper of the fairies. They seem very excited!", e: ["f361"] },
		{ id: "f361", text: "Now I hear a faint squeaking and flapping of wings.", e: ["f362"], typing: 3.0 },
		{ id: "f362", text: "Ohhh, now I can hear them loud and clear! The fairies are flying past me! Freddy did it!", e: ["f363"], typing: 4.0 },
		{ id: "f363", text: "You should be able to see the fairies on the video, if you are interested.", e: ["u364a", "u364b"], typing: 3.0 },
		{ id: "u364a", text: "I'll check it out!", e: ["f365a"] },
		{ id: "u364b", text: "And where is Freddy?", e: ["f365b"] },
		{ id: "f365a", text: "Great!", e: [""] }, //special
		{ id: "f365b", text: "Wait…", e: ["f366"] },
		{ id: "f366", text: "Ah, now I hear him, he's climbing back up out of the window!", e: ["f367"] },
		{ id: "f367", text: "He's back! I'll give him back the button! It was nice talking to you!", e: ["f368"], typing: 4.0 },
		{ id: "f368", text: "I'm back. And I did it! Shall I tell you about it?", e: ["u369a", "u369b", "m"], typing: 4.0 },
		{ id: "u369a", text: "Yes", e: ["f373"] },
		{ id: "u369b", text: "No", e: ["f370"] },
		{ id: "f370", text: "Sure?", e: ["u371a", "u371b"] },
		{ id: "u371a", text: "No", e: ["f372a"] },
		{ id: "u371b", text: "Yes", e: ["f372b"] },
		{ id: "f372a", text: "Okay, then I'll tell you.", e: ["f373"] },
		{ id: "f372b", text: "Then I won't tell you. But the plan worked exactly as we wanted it to!", e: ["f378"] },
		{ id: "f373", text: "I jumped on the researcher's arm as planned. And he reacted exactly as he did last time. He screamed and threw me right against the cage.", e: ["f374"], typing: 5.0 },
		{ id: "f374", text: "Then he ran away. And I was able to open the cage.", e: ["u375a", "u375b"], typing: 4.0 },
		{ id: "u375a", text: "How?", e: ["f376a"] },
		{ id: "u375b", text: "Go on.", e: ["f376a"] },
		{ id: "f376a", text: "With a paper clip that was lying next to it.", e: ["f377"] },
		{ id: "f377", text: "Then all the fairies flew past me.", e: ["f378"], typing: 3.0 },
		{ id: "f378", text: "I did it!", e: ["u379a", "u379b"] },
		{ id: "u379a", text: "Now what?", e: ["f381"] },
		{ id: "u379b", text: "Congratulations!", e: ["f380"] },
		{ id: "f380", text: "Thank you!", e: ["f381"] },
		{ id: "f381", text: "The fairies were very happy to see me and apologized for being so mean to me.", e: ["u382a", "u382b"] },
		{ id: "u382a", text: "Are you friends now?", e: ["f383a"] },
		{ id: "u382b", text: "Devious…", e: ["f383b"] },
		{ id: "f383a", text: "I hope somehow? Or at least that they won't be mean to me anymore.", e: ["f385"] },
		{ id: "f383b", text: "Do think they just said that because they wanted something from me?", e: ["f384"] },
		{ id: "f384", text: "You know, it doesn't really matter to me.", e: ["f385"], typing: 4.0 },
		{ id: "f385", text: "I will see what it's gonna be like once we get back to our forest. Maybe everything will be like it was before, maybe not. We'll see.", e: ["f386"], typing: 5.0 },
		{ id: "f386", text: "But I'll be careful. I don't need fake friends. And I have Benny now!", e: ["u387a", "u387b"], typing: 4.0 },
		{ id: "u387a", text: "So you're going back?", e: ["f388"] },
		{ id: "u387b", text: "Are you rebuilding your hut?", e: ["f388"] },
		{ id: "f388", text: "I think so.", e: ["f389"] },
		{ id: "f389", text: "And I'll ask Benny if he wants to come along. There's room for a second hut.", e: ["f390"] },
		{ id: "f390", text: "Benny says yes! He's coming! We're going to be neighbors!", e: ["u391a", "u391b"] },
		{ id: "u391a", text: "Great!", e: ["f392"] },
		{ id: "u391b", text: "Then get going.", e: ["f392"] },
		{ id: "f392", text: "Thanks for your help, without you I would never have managed all of this!", e: ["f393"] },
		{ id: "f393", text: "If you are ever in the fairy forest, you must come and visit!", e: ["u394a", "u394b"], typing: 4.0 },
		{ id: "u394a", text: "You're welcome.", e: ["f395"] },
		{ id: "u394b", text: "I will!", e: ["f395"] },
		{ id: "f395", text: "See you soon!", e: ["c"] }, //special
];