let msgs = [
		{ id: "f0", text: "Hallo", e: ["f1", "fp1", "r"], typing: 0.0 },
		{ id: "f1", text: "Ist da jemand?", e: ["u2a", "u2b"] },
		{ id: "u2a", text: "Hallo", e: ["f3"] },
		{ id: "u2b", text: "Ja! Was ist los?", e: ["f3"] },
		{ id: "f3", text: "Ich bin Freddy, eine Fee.", e: ["u4a", "u4b"], critical:true },
		{ id: "u4a", text: "Feen gibt es wirklich?", e: ["f5a"] },
		{ id: "u4b", text: "Und was ist los?", e: ["f5b"] },
		{ id: "f5a", text: "Ja, die gibt es! Ein Forscher hat uns gezüchtet und hier auf dieser Insel ausgesetzt um zu schauen, wie wir uns entwickeln.", e: ["f5.1a"] },
		{ id: "f5b", text: "Hier ist ein Forscher, er fängt alle Feen ein!", e: ["f6"], typing: 4.0 },
		{ id: "f5.1a", text: "Aber ich glaube nun ist es so weit...", e: ["f5.2a"] },
		{ id: "f5.2a", text: "Der Forscher probiert uns alle einzufangen!", e: ["f6"] },
		{ id: "f6", text: "Ich habe Angst...", e: ["u7a", "u7b"] },
		{ id: "u7a", text: "Oh nein! Das klingt gefährlich...", e: ["f8"] },
		{ id: "u7b", text: "Hast du schon etwas dagegen getan?", e: ["f8"] },
		{ id: "f8", text: "Die einzige Idee die ich bisher gehabt habe, ist zu probieren, hier im Chat jemanden zu erreichen. Und zum Glück hast du mir geantwortet!", e: ["f9"] },
		{ id: "f9", text: "Kannst du mir vielleicht helfen?", e: ["u10a", "u10b"] },
		{ id: "u10a", text: "Ich weiss nicht wie... ", e: ["f11"] },
		{ id: "u10b", text: "Wie kann ich dir helfen?", e: ["f11"] },
		{ id: "f11", text: "Oh das habe ich fast vergessen! Siehst du die Landkarte?", e: ["u12a", "u12b"] },
		{ id: "u12a", text: "Ja! ", e: ["f14"] },
		{ id: "u12b", text: "Welche Landkarte?", e: ["f13"] },
		{ id: "f13", text: "Die hinter dem Chatfenster. Wenn du auf den kleinen weissen Pfeil klickst, dann kannst du sie besser sehen.", e: ["f14"] },
		{ id: "f14", text: "Auf der Karte sind kleine Kameras abgebildet. Diese kannst du anklicken und sehen, was die Kamera gerade filmt.", e: ["f15"] },
		{ id: "f15", text: "Siehst du die Kamera die blinkt? Wenn du sie anklickst, kannst du mich sehen!", e: ["f16"] }, 
		{ id: "f16", text: "Probiere es aus!", e: [] }, //special
		{ id: "f17", text: "Klicke auf den kleinen weissen Pfeil am Rand des Chatfensters, dann siehst du die ganze Insel. Klicke auf die blinkende Kamera.", e: [] }, //special
		{ id: "f18", text: "Hast du mich gesehen?", e: ["u19a", "u19b"] },
		{ id: "u19a", text: "Ja, hallo Freddy!", e: ["f23"] },
		{ id: "u19b", text: " Nein.", e: ["f20"] },
		{ id: "f20", text: "Ich befinde mich rechts im Bild und winke.", e: ["f21"] },
		{ id: "f21", text: "Schau doch gleich nochmals nach.", e: ["u22b"] },
		{ id: "u22b", text: "Okay", e: [] }, //special
		{ id: "f23", text: "Wenn du auf die andere Kamera gleich daneben klickst, siehst du auch meine tolle Hütte, die ich selbst gebaut habe!", e: ["u24a", "u24b"] },
		{ id: "u24a", text: "Tolle Hütte! ", e: ["f26"] },
		{ id: "u24b", text: "Ich dachte, wir müssen schnell eine Lösung finden?", e: ["f25"] },
		{ id: "f25", text: "Ja, du hast recht!", e: ["f26"] },
		{ id: "f26", text: "Ich könnte mich entweder in meiner Hütte verstecken oder hoch in die Baumwipfel fliegen, wo der Forscher mich nicht erreichen kann. Was meinst du?", e: ["u27a", "u27b"] },
		{ id: "u27a", text: "Hütte", e: ["f28"] },
		{ id: "u27b", text: "Baumwipfel", e: ["f28"] },
		{ id: "f28", text: "Okay, wenn du zusehen möchtest, dann kannst du mich wieder über die Kameraaufnahme beobachten!", e: ["f29"] },
		{ id: "f29", text: "Ich schreibe dir, sobald ich angekommen bin.", e: [] }, //special
		{ id: "f30", text: "Ehmmm", e: ["f31", "fp2"] },
		{ id: "f31", text: "Also der Plan hat nicht so ganz funktioniert...", e: ["u32a", "u32b"] },
		{ id: "u32a", text: "Ich habe es gesehen. ", e: ["f34"] },
		{ id: "u32b", text: "Was ist passiert?", e: ["f33"] },
		{ id: "f33", text: "Ich bin gefallen. Meine Flügel haben mich nicht getragen.", e: ["f34"] },
		{ id: "f34", text: "Ich sitze jetzt neben meiner Hütte unter einem Strauch, hier sieht mich der Forscher auch nicht.", e: ["u35a", "u35b"] },
		{ id: "u35a", text: "Hast du dir weh getan? ", e: ["f36a"] },
		{ id: "u35b", text: "Gut, dann bist du in Sicherheit.", e: ["f36b"] },
		{ id: "f36a", text: "Nein, alles gut, ich bin es gewohnt. Ich bin zum Glück gut gepolstert.", e: ["u37a", "u37b"] },
		{ id: "f36b", text: "Ja, immerhin bin ich an einem ungefährlichen Ort gelandet.", e: ["u37a", "u37b"] },
		{ id: "u37a", text: "Passiert dir das oft?", e: ["f38a"] },
		{ id: "u37b", text: "Gut", e: ["f39"] },
		{ id: "f38a", text: "Ja, jedes Mal! Ich glaube mein Bauch ist zu dick zum Fliegen.", e: ["f39"] },
		{ id: "f39", text: "Oh, ich sehe den Forscher.", e: ["f40", "r"] },
		{ id: "f40", text: "Hahaha weisst du was gerade passiert ist? Ein Käfer ist auf dem Arm des Forschers gelandet! Und der Forscher... Hahaha ich kann nicht mehr!!! Der Forscher kreischt wie ein kleines Mädchen und fuchtelt wild mit den Armen! Und er rennt herum wie ein aufgescheuchtes Huhn!", e: ["f41", "m"] },
		{ id: "f41", text: "Ohhh Achtung er kommt in meine Richtung, ich hoffe er sieht mich nicht!", e: ["f42"], typing: 4.0 },
		{ id: "f42", text: "Nein", e: ["f43"], typing: 5.0 },
		{ id: "f43", text: "Neeeein nein nein", e: ["f44"] },
		{ id: "f44", text: "Das darf nicht wahr sein!", e: ["u45a", "u45b"] },
		{ id: "u45a", text: "Was ist passiert?", e: ["f48"] },
		{ id: "u45b", text: "Haha er hat Angst vor Käfern!", e: ["f46"] },
		{ id: "f46", text: "Ja HAHA aber das ist mir jetzt auch egal. Es ist gerade etwas passiert.", e: ["u47a", "u47b"] },
		{ id: "u47a", text: "Was denn?", e: ["f48"] },
		{ id: "u47b", text: "Erzähl", e: ["f48"] },
		{ id: "f48", text: "Das schlimmste, was hätte passieren können... Meine Hütte... Er ist auf sie draufgetreten! Hast du das gesehen?", e: ["u49a", "u49b"] },
		{ id: "u49a", text: "Nein", e: ["f51"] },
		{ id: "u49b", text: "Ja", e: ["f50"] },
		{ id: "f50", text: "Dann weisst du ja, wie schrecklich es war...", e: ["f51"] },
		{ id: "f51", text: "Sie ist ganz kaputt.", e: ["f52"] },
		{ id: "f52", text: "Mein Ein und Alles...", e: ["f53"] },
		{ id: "f53", text: "Einfach kaputt.", e: ["u54a", "u54b"] },
		{ id: "u54a", text: "Wo ist der Forscher jetzt? ", e: ["f55"] },
		{ id: "u54b", text: "Was machen die anderen Feen?", e: ["f55"] },
		{ id: "f55", text: "Der Forscher hat alle Feen mit einem Netz eingefangen, jetzt ist er weg.", e: ["f56"] },
		{ id: "f56", text: "Aber meine Hütte. Ich habe mir so viel Mühe gegeben und jetzt ist sie einfach kaputt.", e: ["u57a", "u57b"] },
		{ id: "u57a", text: "Wieso ist dir deine Hütte so wichtig?", e: ["f58a"] },
		{ id: "u57b", text: "Alle Feen?", e: ["f58b"] },
		{ id: "f58a", text: "Sie ist alles, was ich habe. Ich kann ja nicht bei den anderen Feen in den Bäumen schlafen, weil ich nicht fliegen kann.", e: ["f59"] },
		{ id: "f58b", text: "Ja, alle Feen, die in der Luft herumgeflogen sind.", e: ["f60"] },
		{ id: "f59", text: "Jetzt bin ich doch froh darüber, dass ich nicht fliegen kann.", e: ["f60"] },
		{ id: "f60", text: "Wenn ich in der Luft gewesen wäre, hätte mich der Forscher sicher auch eingefangen!", e: ["u61a", "u61b"] },
		{ id: "u61a", text: "Rette die Feen! ", e: ["f62a"] },
		{ id: "u61b", text: "Baue deine Hütte auf.", e: ["f62b"] },
		{ id: "f62a", text: "Ehhh wieso? ", e: ["f63a"] },
		{ id: "f62b", text: "Alleine? Das schaffe ich nicht.", e: ["f63b"] },
		{ id: "f63a", text: "Jetzt, da ich endlich meine Ruhe habe? Und nicht die ganze Zeit ihr hämisches Lachen höre, wenn ich probiere, zu fliegen?", e: ["f64a"] },
		{ id: "f63b", text: "Die anderen Feen haben mir beim Bau geholfen. Damit ich nicht mehr bei ihnen in den Bäumen schlafen musste. Sie wollten mich so schnell wie möglich loswerden.", e: ["f64b"], typing: 5.0 },
		{ id: "f64a", text: "Oder eigentlich auch sonst bei allem, was ich mache...", e: ["f66"] },
		{ id: "f64b", text: "Obwohl sie mich jetzt trotzdem immer den ganzen Tag beobachtet haben. Meine Flugversuche fanden sie jedes Mal soooo lustig...", e: ["f65"], typing: 4.0 },
		{ id: "f65", text: "Wie eigentlich auch sonst alles, was ich mache...", e: ["f66"] },
		{ id: "f66", text: "Richtig gemein.", e: ["u67a", "u67b"] },
		{ id: "u67a", text: "Und jetzt? ", e: ["f68"] },
		{ id: "u67b", text: "Wie geht es weiter?", e: ["f68"] },
		{ id: "f68", text: "Gute Frage... Ich kann das Haus nicht alleine aufbauen. Mir ist es jetzt schon langweilig aber die Feen möchte ich nicht zurück. Und einfach nur ein bisschen herumlaufen und nichts tun ist auch blöd...", e: ["f69"], typing: 4.0 },
		{ id: "f69", text: "Ohhh ich habe eine Idee!", e: ["f70"], typing: 5.0 },
		{ id: "f70", text: "Ich werde auch auf dem Haus des Forschers herumtrampeln! Rache!", e: ["u71a", "u71b"] },
		{ id: "u71a", text: "Tolle Idee!", e: ["f74"] },
		{ id: "u71b", text: "Ehm... Also auf dem Dach?", e: ["f72"] },
		{ id: "f72", text: "Ehm... Ja? Wo denn sonst?", e: ["u73a", "u73b"] },
		{ id: "u73a", text: "Gute Idee. Wirklich. Super.", e: ["f74"] },
		{ id: "u73b", text: "Aha...", e: ["f74"] },
		{ id: "f74", text: "Super! Jetzt muss ich nur noch wissen, wo ich hingehen muss.", e: ["f75"] },
		{ id: "f75", text: "Oh Mist! Das wollte ich eigentlich über den Computer in meiner Hütte herausfinden, aber der ist jetzt natürlich auch kaputt!", e: ["u76a", "u76b"] },
		{ id: "u76a", text: "Du hast einen Computer???", e: ["f77a"] },
		{ id: "u76b", text: "Wie schreibst du mir eigentlich?", e: ["f77b"] },
		{ id: "f77a", text: "Ja, den habe ich selber gebaut! Damit kann ich auf die Webseite der Forschungsinsel zugreifen.", e: ["f78a"] },
		{ id: "f77b", text: "Ich habe mich in die Webseite der Forschungsinsel gehackt. Deshalb kann ich dir jetzt über meinen Smartknopf Nachrichten schicken. Wie mit einem Handy, das aussieht wie ein normaler Hosenknopf.", e: ["f78b"], typing: 5.0 },
		{ id: "f78a", text: "Wie auch mit meinem Smartknopf. über den sende ich dir gerade Nachrichten. Er ist wie ein Smartphone, nur in Knopfform. Mit Sprachsteuerung, darauf bin ich besonders stolz!", e: ["f79"] },
		{ id: "f78b", text: "Mit Sprachsteuerung, darauf bin ich besonders stolz!", e: ["f79"], typing: 5.0 },
		{ id: "f79", text: "Die Geschichte dazu findest du auf meinem <a href=\"https://instagram.com/freddysreise/\">Instagram</a> und <a href=\"https://www.facebook.com/freddysreise\">Facebook</a> Profil. Wenn du möchtest, können wir dort Freunde werden!", e: ["u80a", "u80b"], typing: 4.0 },
		{ id: "u80a", text: "Du bist komisch...", e: ["f81"] }, 
		{ id: "u80b", text: "Was? Wirklich?", e: ["f81"] },
		{ id: "f81", text: "Irgendwas muss ich ja tun mit meiner Zeit. Freunde habe ich ja keine...", e: ["f82"] },
		{ id: "f82", text: "Aber zurück zu meinem Racheplan.", e: ["f83"] },
		{ id: "f83", text: "Du kannst ja auf die Webseite und die Kameras zugreifen! So brauche ich meinen Computer gar nicht. Du kannst mir sagen, was ich tun soll.", e: ["u84a", "u84b"], typing: 4.0 },
		{ id: "u84a", text: "Wie?", e: ["f85"] },
		{ id: "u84b", text: "Mach ich!", e: ["f85"] },
		{ id: "f85", text: "Du kannst auf alle Kameras klicken. Dann kannst du sehen, was dort gerade passiert.", e: ["f86", "m"] },
		{ id: "f86", text: "Weisst du noch wie?", e: ["u87a", "u87b"] },
		{ id: "u87a", text: "Ja", e: ["f88a"] },
		{ id: "u87b", text: "Nein", e: ["f88b"] },
		{ id: "f88a", text: "Super!", e: ["f89"] },
		{ id: "f88b", text: "Hinter dem Chatfenster hat es eine Karte. Wenn du oben rechts auf den kleinen Pfeil nach unten klickst, kannst du sie besser sehen. Dann kannst du auf die Kameras klicken.", e: ["f89"] },
		{ id: "f89", text: "Schau doch mal nach, ob du in einem Video einen Hinweis findest, wohin der Forscher gegangen ist! Wohin soll ich gehen? Auf der Karte nach oben, unten oder nach rechts?", e: ["u90a", "u90b", "u90c"], typing: 4.0 },
		{ id: "u90a", text: "Oben", e: ["f91", "fp3"] },
		{ id: "u90b", text: "Unten", e: ["f94", "fp4"] },
		{ id: "u90c", text: "Rechts", e: ["f97", "fp5"] },
		{ id: "f91", text: "Hier komme ich nicht weiter. Siehst du?", e: ["f92"] },
		{ id: "f92", text: "Ich stehe vor einer steilen Felswand, da komme ich nicht hoch...", e: ["f93"] },
		{ id: "f93", text: "Schau doch mal ganz genau auf den anderen Aufnahmen nach. Hoffentlich findest du so einen Hinweis!", e: ["u90b", "u90c"] },
		{ id: "f94", text: "Hier komme ich nicht weiter. Siehst du?", e: ["f95"] },
		{ id: "f95", text: "Ich stehe an einer Klippe, da komme ich nicht hinunter. Und sowieso ist da nur noch das Meer.", e: ["f96"] },
		{ id: "f96", text: "Schau doch mal ganz genau auf den anderen Aufnahmen nach. Hoffentlich findest du so einen Hinweis!", e: ["u90a", "u90c"] },
		{ id: "f97", text: "Okay, dann schaue ich doch mal, was du gefunden hast!", e: ["f98"] },
		{ id: "f98", text: "Oha, da ist es recht sumpfig, ich hoffe, der Boden hält...", e: ["u99a", "u99b"] },
		{ id: "u99a", text: "Bleib am Rand ", e: ["f100"] },
		{ id: "u99b", text: "Mach kleine Schritte", e: ["f100"] },
		{ id: "f100", text: "Okay... Ich bin ganz vorsichtig.", e: ["f101"] },
		{ id: "f101", text: "Ich kann blöderweise auch meine Füsse nicht sehen, mein Bauch ist im Weg...", e: ["f102"] },
		{ id: "f102", text: "Oh nein!!!", e: ["u103a", "u103b", "m"] },
		{ id: "u103a", text: "Was?", e: ["f105"] },
		{ id: "u103b", text: "Bist du steckengeblieben?", e: ["f104"] },
		{ id: "f104", text: "Ja!", e: ["f105"] },
		{ id: "f105", text: "Ich bin steckengeblieben.", e: ["f106"] },
		{ id: "f106", text: "Was soll ich nur tun?", e: ["u107a", "u107b"] },
		{ id: "u107a", text: "Arme bewegen", e: ["f108"] },
		{ id: "u107b", text: "Nicht bewegen!", e: ["f109"] },
		{ id: "f108", text: "Oh nein, ich sinke immer schneller!", e: ["f109"] },
		{ id: "f109", text: "Was jetzt?", e: ["u110a", "u110b"] },
		{ id: "u110a", text: "Rufe um Hilfe!", e: ["f113"] },
		{ id: "u110b", text: "Ich schau auf den Kameras nach!", e: ["f111"] },
		{ id: "f111", text: "Super danke, das ist eine gute Idee!", e: [] },
		{ id: "u112", text: "Dort sind Bienen. Rufe um Hilfe!", e: ["f113"] },
		{ id: "f113", text: "Nein! Ich möchte nicht, dass sich jemand über die dicke Fee lustig macht, die im Sumpf feststeckt.", e: ["f114"] },
		{ id: "f114", text: "Und falls das nicht klar war: Mit der dicken Fee meine ich mich. :-(", e: ["u115a" ,"u115b"] },
		{ id: "u115a", text: "Ach Freddy...", e: ["f116"] }, 
		{ id: "u115b", text: "Ich möchte helfen.", e: ["f116"] }, 
		{ id: "f116", text: "Schau bitte nach, ob du in einem Überwachungsvideo etwas siehst, was mir helfen könnte.", e: ["u117"] },
		{ id: "u117", text: "Okay", e: [""] }, //special
		{ id: "u118", text: "Da ist eine Biene mit Blindenstock.", e: ["f119"] },
		{ id: "f119", text: "Eine blinde Biene?", e: ["f120"] },
		{ id: "f120", text: "Hm okay, die könnte ich rufen. Die lacht bestimmt nicht über mich, wenn sie mich nicht sehen kann.", e: ["f121"] },
		{ id: "f121", text: "Moment, ich schreibe dir nachher wieder.", e: ["m"], critical:true }, //special
		{ id: "f122", text: "Okay, ich habe es getan. Ich habe die Biene gerufen.", e: ["f123"], typing: 4.0 },
		{ id: "f123", text: "Die Biene heisst Benny.", e: ["f124"] },
		{ id: "f124", text: "Er hat mir geholfen, ich bin wieder frei!", e: ["u125a", "u125b"] },
		{ id: "u125a", text: "Ohne zu sehen?", e: ["f126"] },
		{ id: "u125b", text: "Super!", e: ["f127"] },
		{ id: "f126", text: "Ich habe ihm genau gesagt, wo er durchfliegen und was er tun muss.", e: ["f127"] },
		{ id: "f127", text: "Ich habe ihm von dir erzählt, er fand es nämlich komisch, dass ich mit mir selber rede.", e: ["f128"], typing: 4.0 },
		{ id: "f128", text: "Wegen der Spracheingabe meines Smartknopfes meine ich.", e: ["f129"], typing: 3.0 },
		{ id: "f129", text: "Und ich habe ihm von meinem Racheplan erzählt.", e: ["f130"], typing: 3.0 },
		{ id: "f130", text: "Benny sagt, er habe den Forscher mit den Feen gehört. Er wisse, wo der Forscher wohne.", e: ["f131"], typing: 3.0 },
		{ id: "f131", text: "Soll ich ihn fragen, ob er uns den Weg zeigen kann?", e: ["u132a", "u132b"] },
		{ id: "u132a", text: "Er hat sicher besseres zu tun.", e: ["f133"] },
		{ id: "u132b", text: "Ja!", e: ["f134"] },
		{ id: "f133", text: "Oh, er hat es gehört, als ich dich gefragt habe. Die Sprachsteuerung hat also auch Nachteile.", e: ["f134"] },
		{ id: "f134", text: "Er sagt, er möchte gerne mitkommen! Super!", e: ["u135a", "u135b"] },
		{ id: "u135a", text: "Gehen wir!", e: ["f136a"] },
		{ id: "u135b", text: "Lieb von ihm.", e: ["f136b"] },
		{ id: "f136a", text: "Schon gut, schon gut, wir sind ja schon auf dem Weg!", e: ["f137"] },
		{ id: "f136b", text: "Ja, das finde ich auch!", e: ["f137"] },
		{ id: "f137", text: "Ich glaube, wir werden uns gut verstehen.", e: ["f138"] },
		{ id: "f138", text: "Benny sagt, dass er noch nie so weit von seinem Zuhause weg gewesen wäre, so ganz ohne die anderen Bienen.", e: ["u139a", "u139b"], typing: 4.0 },
		{ id: "u139a", text: "Wieso kennt er den Weg?", e: ["f140"] },
		{ id: "u139b", text: "Okay.", e: ["f141"] },
		{ id: "f140", text: "Er kann die Blumen auf dem Weg riechen. Alle duften anders. Ich rieche das leider nicht so gut wie er.  ", e: ["f141"] },
		{ id: "f141", text: "Oh ich sehe ein Hausdach in der Ferne. Ich kann es kaum erwarten, darauf herum zu trampeln!", e: ["f142"], typing: 4.0 },
		{ id: "f142", text: "Muahahahaha", e: ["f143"] },
		{ id: "f143", text: "Ich hoffe, du hast das gerade in deiner bösesten Stimme gelesen. Das war mein Bösewicht-Lachen.", e: ["f144"], typing: 4.0 },
		{ id: "f144", text: "Benny sagt, dass wir gleich dort sind.", e: ["u145a", "u145b"] },
		{ id: "u145a", text: "Kannst du so hoch klettern?", e: ["f146"] },
		{ id: "u145b", text: "Was machst du nach der Rache?", e: ["f146"] },
		{ id: "f146", text: "Moment.", e: ["f147", "m"] },
		{ id: "f147", text: "Benny, ich komme da nicht durch, da ist ein Abgrund! Was? Das wusste ich nicht! Ich fliege da immer ganz normal durch. Aber Benny!", e: ["u148a",  "u148b"] },
		{ id: "u148a", text: "Hallo Freddy?", e: ["f149"] },
		{ id: "u148b", text: "Was ist los?", e: ["f149"] },
		{ id: "f149", text: "Oh, ich hatte die Spracheingabe noch an. Sie hat dir das Gespräch von Benny und mir gesendet. Ups.", e: ["f150"] },
		{ id: "f150", text: "Etwas ganz schlimmes ist passiert! Kannst du mich auf der Kamera sehen? Ich sehe, dass dort eine hängt.", e: ["u151a", "u151b", "fp6"] },
		{ id: "u151a", text: "Jetzt sag schon.", e: ["f152"] },
		{ id: "u151b", text: "Okay, ich sehe nach.", e: [""] }, //special
		{ id: "f152", text: "Zwischen uns und dem Haus ist ein Abgrund.", e: ["f153"] },
		{ id: "f153", text: "Ich komme da nicht durch. Benny kann fliegen, für ihn ist das kein Problem. Aber ich möchte es nicht probieren und dabei in die Tiefe stürzen… Im Wald geht das ja noch, aber hier unten sind nur Steine und ein Fluss!", e: ["f154"], typing: 5.0 },
		{ id: "f154", text: "Tiiiiiief unten.", e: ["u155a", "u155b"], typing: 4.0 },
		{ id: "u155a", text: "Kann dich Benny hinüberfliegen?", e: ["f156a"] },
		{ id: "u155b", text: "Schön blöd. Dann geh nach Hause.", e: ["f156b"] },
		{ id: "f156a", text: "Hast du gesehen, wie klein er ist? Und wie gross ich bin?", e: ["f157a"] },
		{ id: "f156b", text: "Und was ist mit meinem Racheplan?", e: ["f157b"] },
		{ id: "f157a", text: "Nein, ich bin zu schwer für Benny.", e: ["f158"] },
		{ id: "f157b", text: "Ich gebe den nicht auf. Niemals!", e: ["f158"] },
		{ id: "f158", text: "Wir brauchen eine andere Lösung. Hier liegen Äste herum und das hohe Gras können wir bestimmt auch für etwas gebrauchen.", e: ["f159"], typing: 4.0 },
		{ id: "f159", text: "Was meinst du?", e: ["u160a", "u160b"] },
		{ id: "u160a", text: "Das Gras als Schnur verwenden.", e: ["f161a"] },
		{ id: "u160b", text: "Einen Ast als Brücke brauchen.", e: ["f161b"] },
		{ id: "f161a", text: "Das ist eine tolle Idee!", e: ["f162"] },
		{ id: "f161b", text: "Hast du gesehen, wie kurz die Stöcke sind? Die sind viel zu kurz und reichen nicht bis zur anderen Seite.", e: ["f162"] },
		{ id: "f162", text: "Ich könnte entweder die einzelnen Äste aneinanderbinden, damit ich einen Stab habe und darauf bis zur anderen Seite balancieren kann. Das würde sehr schnell gehen.", e: ["f163"], typing: 5.0 },
		{ id: "f163", text: "Oder ich baue eine Hängebrücke. Das würde viel länger dauern. Aber dafür wäre es stabiler und weniger gefährlich.", e: ["f164"], typing: 4.0 },
		{ id: "f164", text: "Bitte entscheide du für mich.", e: ["u165a", "u165b"] },
		{ id: "u165a", text: "Stab", e: ["f166"] },
		{ id: "u165b", text: "Hängebrücke", e: ["f187"] },
		//Stab:
		{ id: "f166", text: "Okay, dann binde ich die Äste mit Gras zusammen.", e: ["f167"] },
		{ id: "f167", text: "Ich hoffe, das hält nur mit einem Grashalm als Schnur…", e: ["u168a", "u168b"], typing: 3.0  },
		{ id: "u168a", text: "Nimm mehrere.", e: ["f169a"] },
		{ id: "u168b", text: "Das geht schon.", e: ["f169b"] },
		{ id: "f169a", text: "Das ist eine gute Idee. So ist es bestimmt stabiler.", e: ["f170"] },
		{ id: "f169b", text: "Okay, ich hoffe du hast recht…", e: ["f170"] },
		{ id: "f170", text: "Ich glaube so lang sollte reichen.", e: ["f171"], typing: 3.0  },
		{ id: "f171", text: "Ich frage Benny, ob er neben mir herfliegen kann, nur für alle Fälle.", e: ["f172"], typing: 4.0  },
		{ id: "f172", text: "Ohh und es ist wackelig, ich halte mich lieber an seiner Hand fest.", e: ["u173a", "u173b"], typing: 4.0  },
		{ id: "u173a", text: "Haha du hast Angst!", e: ["f174a"] },
		{ id: "u173b", text: "Sicherheit geht vor!", e: ["f174b"] },
		{ id: "f174a", text: "Denk daran, wenn ich hinunterfalle dann ist das deine Schuld, du hast gesagt, dass ich die Stöcke zusammenbinden soll!", e: ["f175"] },
		{ id: "f174b", text: "Ja finde ich auch.", e: ["f175"] },
		{ id: "f175", text: "Ich habe ein kleines Problem. Mein Smartknopf, mit dem ich dir Nachrichten schicke, ist zu schwer, er bringt mich ganz aus dem Gleichgewicht.", e: ["f176"], typing: 4.0 },
		{ id: "f176", text: "Ich muss ihn leider hierlassen.", e: ["u177a", "u177b"], typing: 3.0 },
		{ id: "u177a", text: "Viel Erfolg noch.", e: ["f178"] },
		{ id: "u177b", text: "Neiiin Freddy, verlass mich nicht!", e: ["f178"] },
		{ id: "f178", text: "Du kannst mich ja immer noch auf den Kameras beobachten.", e: ["f179"] },
		{ id: "f179", text: "Also, ich gehe dann mal. Klick auf die Kamera beim Abgrund, dann siehst du, wie ich hinübergehe.", e: [""], critical:true }, //special
		{ id: "f180", text: "Da bin ich schon wieder, das war wohl eine kurze Trennung…", e: ["u181a", "u181b"] },
		{ id: "u181a", text: "Geht es dir gut?", e: ["f182a"] },
		{ id: "u181b", text: "Was ist passiert?", e: ["f182b"] },
		{ id: "f182a", text: "Ja, Benny hat mich gerettet.", e: ["f183"] },
		{ id: "f182b", text: "Ich bin vom Stab gekippt, mein Gleichgewicht ist leider nicht so gut. Zum Glück hat Benny mich gefangen.", e: ["f183"] },
		{ id: "f183", text: "Da habe ich nochmals Glück gehabt!", e: ["u184a", "u184b"] },
		{ id: "u184a", text: "Gut!", e: ["f185"] },
		{ id: "u184b", text: "Und jetzt?", e: ["f185"] },
		{ id: "f185", text: "Ich habe dich entscheiden lassen und das hätte mich fast umgebracht. Jetzt entscheide ich. Ich werde die Hängebrücke bauen. Das dauert zwar länger aber dann falle ich immerhin nicht noch einmal hinunter!", e: ["u186a", "u186b"] },
		{ id: "u186a", text: "Wie du meinst.", e: ["f187"] },
		{ id: "u186b", text: "Gute Idee!", e: ["f187"] },
		//Hängebrücke:
		{ id: "f187", text: "Okay, bauen wir eine Hängebrücke. Wir schaffen das!", e: ["f188"] }, 
		{ id: "f188", text: "Ich frage Benny, ob er mir helfen kann. Knüpfen kann er ja auch, ohne sehen zu müssen.", e: ["u189a", "u189b"], typing: 3.0 },
		{ id: "u189a", text: "Weisst du, wie das geht?", e: ["f190"] },
		{ id: "u189b", text: "Gut.", e: ["f192"] },
		{ id: "f190", text: "Also ich habe schon einmal eine Hängebrücke gebaut. Weisst du, als ich nicht mehr fliegen konnte, da habe ich am Anfang noch bei den anderen Feen oben im Baum gewohnt. Und damit ich dorthin kam, habe ich Brücken zwischen den verschiedenen Bäumen gebaut.", e: ["f191"], typing: 4.0  },
		{ id: "f191", text: "Die Geschichte dazu habe ich auf meinen Social-Media-Kanälen erzählt. Ich heisse auf <a href=\"https://instagram.com/freddysreise/\">Instagram</a> und <a href=\"https://www.facebook.com/freddysreise\">Facebook</a> @freddysreise, falls du es dir anschauen möchtest!", e: ["f192"], typing: 5.0  },
		{ id: "f192", text: "Ich bin so froh, dass Benny mitgekommen ist. Alleine hätte mich der Mut bestimmt schon wieder verlassen. Wie es den Feen wohl ergangen ist?", e: ["u193a", "u193b"], typing: 4.0 },
		{ id: "u193a", text: "Benny ist toll!", e: ["f198"] },
		{ id: "u193b", text: "Die armen Feen.", e: ["f194"] },
		{ id: "f194", text: "Sie waren immer so gemein zu mir aber jetzt tun sie mir schon ein bisschen Leid…", e: ["u195a", "u195b"] },
		{ id: "u195a", text: "Rette sie!", e: ["f196a"] },
		{ id: "u195b", text: "Sie haben es verdient.", e: ["f196b"] },
		{ id: "f196a", text: "Hmm ich weiss nicht… Damit sie mich dann wieder auslachen können? Nein ich denke besser nicht.", e: ["f197"] },
		{ id: "f196b", text: "Du hast ja recht.", e: ["f197"] },
		{ id: "f197", text: "Zum Glück ist Benny anders.", e: ["f198"], typing: 3.0  },
		{ id: "f198", text: "Ich hatte noch nie so einen guten Freund wie ihn… Ich glaube, ich möchte ihm davon erzählen, wie mich die Feen behandelt haben.", e: ["u199a", "u199b"] },
		{ id: "u199a", text: "Ja mach das!", e: ["f200a"] },
		{ id: "u199b", text: "Baut zuerst die Brücke fertig.", e: ["f200b"] },
		{ id: "f200a", text: "Benny hat gerade vorgeschlagen, dass wir in der Pfütze dort drüben baden gehen könnten. Das finde ich gut, dann kann ich ihm dabei meine Geschichte erzählen.", e: ["f204"] },
		{ id: "f200b", text: "Okay wenn du meinst. Aber bevor Benny zur anderen Seite fliegt, machen wir eine Pause.", e: ["f201"] },
		{ id: "f201", text: "Es ist sooo heiss.", e: ["f202"], typing: 3.0  },
		{ id: "f202", text: "Ich sehe eine Pfütze. Wir können darin baden!", e: ["f203"], typing: 3.0  },
		{ id: "f203", text: "Benny findet das eine gute Idee.", e: ["f204"], typing: 3.0  },
		{ id: "f204", text: "Haha weisst du was? Ich kann mir sogar problemlos die Hose ausziehen, damit sie nicht nass wird. Benny sieht mich ja sowieso nicht!", e: ["u205a", "u205b"], typing: 4.0 },
		{ id: "u205a", text: "Wie praktisch!", e: ["f206"] },
		{ id: "u205b", text: "So toll!", e: ["f206"] },
		{ id: "f206", text: "Finde ich auch!", e: ["f207"] },
		{ id: "f207", text: "Okay, ich sitze in der Pfütze, meinen Smartknopf habe ich neben mir, damit ich dich auf dem Laufenden halten kann, was das Gespräch angeht.", e: ["f208"], typing: 4.0 },
		{ id: "f208", text: "Also, ich erzähle Benny, dass die Feen immer über mich lachen.", e: ["f209"], typing: 4.0 },
		{ id: "f209", text: "Benny fragt, weshalb.", e: ["f210"], typing: 4.0 },
		{ id: "f210", text: "Was soll ich sagen?", e: ["u211a", "u211b"], typing: 4.0 },
		{ id: "u211a", text: "Wegen deinem runden Bauch.", e: ["f212"] },
		{ id: "u211b", text: "Wegen deiner Kartoffelnase.", e: ["f212"] },
		{ id: "f212", text: "Okay, ich habe es gesagt.", e: ["f213"] },
		{ id: "f213", text: "Oh nein!!!", e: ["f214"], typing: 4.0 },
		{ id: "f214", text: "Nein nein nein nein nein!", e: ["f215"], typing: 4.0 },
		{ id: "f215", text: "Ein Vogel hat meine Hose geklaut!", e: ["f216"], typing: 3.0 },
		{ id: "f216", text: "Und ich habe sie nicht mehr erwischt…", e: ["f217"] },
		{ id: "f217", text: "Jetzt muss ich meinen Rachefeldzug nackt beenden!", e: ["u218a", "u218b", "m"], typing: 3.0 },
		{ id: "u218a", text: "Hahahahaha", e: ["f219a"] },
		{ id: "u218b", text: "Oh nein!", e: ["f219b"] },
		{ id: "f219a", text: "Benny lacht mich auch aus!", e: ["f220"] },
		{ id: "f219b", text: "Weisst du wie Benny auf meine Geschichte reagiert? Er lacht mich aus!", e: ["f220"] },
		{ id: "f220", text: "Wie kann er nur! Ich dachte, er wäre anders. Endlich finde ich jemanden, dem ich vertraue und er lacht einfach über mich. Ich dachte, dass es ihm egal ist, wie ich aussehe, aber scheinbar nicht! Er hat es einfach nicht gewusst und jetzt, wo er es weiss, lacht auch er über mich.", e: ["f221"], typing: 5.0 },
		{ id: "f221", text: "Es sind doch alle gleich!", e: ["f222"], typing: 4.0 },
		{ id: "f222", text: "Soll er doch nur weggehen, ich brauche keine solchen Freunde!", e: ["u223a", "u223b"], typing: 3.0 },
		{ id: "u223a", text: "Warte!", e: ["f224"] },
		{ id: "u223b", text: "Tu das nicht!", e: ["f224"] },
		{ id: "f224", text: "Was denn?", e: ["f225"] },
		{ id: "f225", text: "So, jetzt ist er weg der Verräter!", e: ["u226a", "u226b"] },
		{ id: "u226a", text: "Nein, Freddy!", e: ["f227"] },
		{ id: "u226b", text: "Wieso?", e: ["f227"] },
		{ id: "f227", text: "Er hat mich ausgelacht, er hat es verdient!", e: ["u228a", "u228b"] },
		{ id: "u228a", text: "Er ist dein Freund!", e: ["f229"] },
		{ id: "u228b", text: "Er hat nicht über dich gelacht!", e: ["f230"] },
		{ id: "f229", text: "Aber er hat gelacht!", e: ["f230"] },
		{ id: "f230", text: "Über was sollte er sonst gelacht haben?", e: ["u231a", "u231b"] },
		{ id: "u231a", text: "Nackt auf dem Dach hüpfen.", e: ["f232"] },
		{ id: "u231b", text: "Nacktheit ist lustig.", e: ["f232"] },
		{ id: "f232", text: "Haha", e: ["f233"] },
		{ id: "f233", text: "Hm schon ja, aber was hat das miteinander zu tun?", e: ["f234"], typing: 3.0 },
		{ id: "f234", text: "Ahhhhh okay", e: ["f235"], typing: 4.0 },
		{ id: "f235", text: "Ich verstehe, was du meinst.", e: ["f236"], typing: 3.0 },
		{ id: "f236", text: "Er hat gar nicht über mich gelacht, sein Lachen hatte nichts mit meiner Geschichte zu tun!", e: ["u237a", "u237b"], typing: 4.0 },
		{ id: "u237a", text: "Suche Benny", e: ["f238a"] },
		{ id: "u237b", text: "Suche zuerst deine Hose", e: ["f238b"] },
		{ id: "f238a", text: "Okay, Benny ist in Richtung der Berge davongeflogen. Siehst du ihn auf einer Aufnahme?", e: ["u240a"] },
		{ id: "f238b", text: "Okay, die Vögel sind in Richtung der Berge davongeflogen. Siehst du sie oder meine Hose auf der Aufnahme einer Kamera?", e: ["u240a", "u240b"] },
		{ id: "u240a", text: "Nein", e: ["f241"] },
		{ id: "u240b", text: "Dort gibt es keine Kameras.", e: ["f241"] },
		{ id: "f241", text: "Blöd…", e: ["f242"] },
		{ id: "f242", text: "Was mache ich denn nun? Ich bin nackt, alleine, und weil die Brücke noch nicht auf der anderen Seite befestigt ist, kann ich meinen Racheplan auch nicht fortsetzen…", e: ["u243a", "u243b"], typing: 4.0 },
		{ id: "u243a", text: "Warte, er kommt bestimmt zurück.", e: ["f244a"] },
		{ id: "u243b", text: "Rufe ihn.", e: ["f244b"] },
		{ id: "f244a", text: "Ich hoffe es. Ich weiss nicht, was ich ohne ihn tun soll…", e: ["f247"] },
		{ id: "f244b", text: "Okay, ich rufe so laut ich kann.", e: ["f245"] },
		{ id: "f245", text: "Nichts. Ich höre mein eigenes Echo aber Benny sehe ich weit und breit nicht.", e: ["f246"], typing: 4.0 },
		{ id: "f246", text: "Ich hoffe, er kommt zurück. Ich weiss nicht, was ich ohne ihn tun soll…", e: ["f247"], typing: 4.0 },
		{ id: "f247", text: "Ich warte in der Pfütze, da sieht man wenigstens nicht, dass ich nackt bin.", e: ["u248a", "u248b"], typing: 4.0 },
		{ id: "u248a", text: "Was tust du, falls Benny nicht kommt?", e: ["f249"] },
		{ id: "u248b", text: "Gute Idee.", e: ["f252"] },
		{ id: "f249", text: "Dann werde ich wohl oder übel nach Hause zurückgehen müssen.", e: ["u250a", "u250b"] },
		{ id: "u250a", text: "Okay", e: ["f252"] },
		{ id: "u250b", text: "Ohne Haus?", e: ["f251"] },
		{ id: "f251", text: "Stimmt, das kann ich ja alleine auch nicht mehr aufbauen…", e: ["f252"] },
		{ id: "f252", text: "Etwas kommt auf mich zugeflogen.", e: ["f253"] },
		{ id: "f253", text: "Was ist das? Es sieht fast aus wie ein grosser grüner Ballon…", e: ["f254"], typing: 4.0 },
		{ id: "f254", text: "Mit Streifen darauf.", e: ["f255"] },
		{ id: "f255", text: "Oh, weisst du was? Das ist meine Hose!", e: ["u256a", "u256b"], typing: 4.0 },
		{ id: "u256a", text: "Eine fliegende Hose?", e: ["f257"] },
		{ id: "u256b", text: "Häh?", e: ["f257"] },
		{ id: "f257", text: "Nicht nur meine Hose! Benny!!!", e: ["f258", "m"] },
		{ id: "f258", text: "Benny bringt mir meine Hose zurück!", e: ["u259a", "u259b"] },
		{ id: "u259a", text: "Wie toll!", e: ["f260a"] },
		{ id: "u259b", text: "Entschuldige dich!", e: ["f260b"] },
		{ id: "f260a", text: "Ja!", e: ["f261a"] },
		{ id: "f260b", text: "Okay, ich schreie ihm entgegen, wie leid es mir tut!", e: ["f261b"] },
		{ id: "f261a", text: "Er hat sie mir gegeben.", e: ["u262a", "u262b"], typing: 4.0 },
		{ id: "f261b", text: "Er schreit zurück, er verzeiht mir!", e: ["f263"], typing: 4.0 },
		{ id: "u262a", text: "Was sagt er?", e: ["f265"] },
		{ id: "u262b", text: "Entschuldige dich!", e: ["f264"] },
		{ id: "f263", text: "Jetzt wird alles wieder gut!", e: ["f265"], typing: 3.0 },
		{ id: "f264", text: "Okay, mache ich.", e: ["f265"] },
		{ id: "f265", text: "Er sagt, es ist nicht schlimm, was ich getan habe. Er weiss, dass es nicht leicht ist, anders zu sein.", e: ["f266"], typing: 4.0 },
		{ id: "f266", text: "Für Benny hat es nie eine Rolle gespielt, wie ich aussehe. Ihm ist es egal, wie breit oder schmal ich bin. Er sagt, dass unser Aussehen uns nicht zu dem macht, was wir sind. Was wir in uns drin haben ist wichtiger.", e: ["u267a", "u267b"], typing: 5.0 },
		{ id: "u267a", text: "So schön!", e: ["f268a"] },
		{ id: "u267b", text: "Unsere Organe?", e: ["f268b"] },
		{ id: "f268a", text: "Finde ich auch.", e: ["f269"] },
		{ id: "f268b", text: "Nein, er meint unsere Persönlichkeit.", e: ["f269"] },
		{ id: "f269", text: "Ich bin so froh, dass wir wieder Freunde sind!", e: ["u270a", "u270b"] },
		{ id: "u270a", text: "Ich auch!", e: ["f272"] },
		{ id: "u270b", text: "Hast du deine Hose wieder an?", e: ["f271"] },
		{ id: "f271", text: "Ja habe ich. Über Benny habe ich mich trotzdem mehr gefreut.", e: ["f272"] },
		{ id: "f272", text: "Okay, zurück zum Plan. Benny ist jetzt zur anderen Seite des Abgrunds hinübergeflogen und bindet die Brücke fest.", e: ["f273"], typing: 3.0 },
		{ id: "f273", text: "Ich hoffe, die Brücke hält. Schau dir doch die Aufnahme der Überwachungskamera an, dann weisst du gleich, ob ich es geschafft habe!", e: ["u274a", "u274b"], typing: 4.0 },
		{ id: "u274a", text: "Mach ich!", e: ["f275a"] },
		{ id: "u274b", text: "Keine Lust.", e: ["f275b"] },
		{ id: "f275a", text: "Super! Ich schreibe dir wieder, wenn ich auf der anderen Seite bin.", e: [""] }, //special
		{ id: "f275b", text: "Okay. Ich schreibe dir wieder, wenn ich auf der anderen Seite bin.", e: [] }, //special
		//Haus
		{ id: "f276", text: "Super, ich bin drüben! Wir stehen jetzt vor dem Haus des Forschers.", e: ["f277", "m", "fp7"], typing: 4.0 }, //ab hier forscher ambi
		{ id: "f277", text: "Sollen wir zuerst darum herum gehen und schauen, ob wir alleine sind oder gleich hochklettern?", e: ["u278a", "u278b"], typing: 4.0 },
		{ id: "u278a", text: "Um das Haus herum gehen", e: ["f279a"] },
		{ id: "u278b", text: "Hochklettern", e: ["f279b"] },
		{ id: "f279a", text: "Ist vielleicht besser, wenn wir wissen, ob wir alleine sind.", e: ["f280"] },
		{ id: "f279b", text: "Also, los!", e: ["f284"] },
		{ id: "f280", text: "Da ist eine grosse Eingangstür.", e: ["u281a", "u281b"], typing: 3.0 },
		{ id: "u281a", text: "Siehst du etwas?", e: ["f282a"] },
		{ id: "u281b", text: "Öffne sie.", e: ["f282b"] },
		{ id: "f282a", text: "Da stehen zwei grosse, schlammige Schuhe vor der Tür. Von diesen Schuhen stammt bestimmt der Abdruck, den wir bei den Bienen gesehen haben!", e: ["f283"] },
		{ id: "f282b", text: "Das geht nicht, sie ist zu schwer.", e: ["f283"] },
		{ id: "f283", text: "Also, klettern wir hoch.", e: ["f284"], typing: 4.0 },
		{ id: "f284", text: "Das ist noch schwierig…", e: ["f285"], typing: 3.0 },
		{ id: "f285", text: "Soll ich Benny fragen, ob er mir helfen kann?", e: ["u286a", "u286b"], typing: 3.0 },
		{ id: "u286a", text: "Ja, tu das.", e: ["f287a"] },
		{ id: "u286b", text: "Du schaffst das alleine!", e: ["f287b"] },
		{ id: "f287a", text: "Gut, so ist es einfacher.", e: ["f288"] },
		{ id: "f287b", text: "Du hast recht, ich bin eine selbständige Fee. Ich schaffe das!", e: ["f288"] },
		{ id: "f288", text: "Puh, war das anstrengend.", e: ["f289"], typing: 3.0 },
		{ id: "f289", text: "Oh, da sehe ich wieder eine Kamera, so kannst du mich wieder beobachten.", e: ["f290"], typing: 4.0 },
		{ id: "f290", text: "Ich sehe durch das Fenster des Forschungslabors! Und da sind die Feen!", e: ["u291a", "u291b"], typing: 4.0 },
		{ id: "u291a", text: "Wo?", e: ["f292"] },
		{ id: "u291b", text: "Ich sehe sie!", e: ["f293"] },
		{ id: "f292", text: "Du kannst sie über die Kamera, die neben dem Haus abgebildet ist sehen. Sie sind in einem Käfig und sehen ganz unglücklich aus...", e: ["f293"] },
		{ id: "f293", text: "Jetzt fühle ich mich noch schlechter. Soll ich sie befreien oder mich lieber beim Forscher rächen?", e: ["u294a", "u294b"] },
		{ id: "u294a", text: "Helfen", e: ["f295"] },
		{ id: "u294b", text: "Rache", e: ["f297"] },
		{ id: "f295", text: "Und meinen Racheplan einfach vergessen?", e: ["u296a", "u296b"] },
		{ id: "u296a", text: "Ja!", e: ["f304"] },
		{ id: "u296b", text: "Nein!", e: ["f297"] },
		{ id: "f297", text: "Okay, dann klettere ich auf das Dach.", e: ["f298"] },
		{ id: "f298", text: "Ich bin oben! Und los!", e: ["f299"], typing: 3.0 },
		{ id: "f299", text: "Muahahaha! Wie du mir, so ich dir! Geschieht dir ganz recht!", e: ["f299.5"], typing: 4.0 },
		{ id: "f299.5", text: "Wieso kann ich das nur nicht so geniessen wie ich dachte?", e: ["u300a", "u300b"], typing: 4.0 },
		{ id: "u300a", text: "Blöde Idee", e: ["f301"] },
		{ id: "u300b", text: "Das war genug lang.", e: ["f301"] },
		{ id: "f301", text: "Ich glaube, ich weiss was los ist… Ich fühle mich schlecht wegen den Feen. Als ich alleine vor dem Abgrund stand, kam Benny, um mir zu helfen.", e: ["f302"] },
		{ id: "f302", text: "So jemanden brauchen sie auch!", e: ["u303a", "u303b"], typing: 4.0 },
		{ id: "u303a", text: "Sei ihr Held!", e: ["f304"] },
		{ id: "u303b", text: "Wenn du meinst…", e: ["f304"] },
		{ id: "f304", text: "Okay, ich werde sie retten! Aber wie?", e: ["u305a", "u305b"] },
		{ id: "u305a", text: "Schau das Labor an.", e: ["f305a"] },
		{ id: "u305b", text: "Geh einfach.", e: ["f305b"] },
		{ id: "f305a", text: "Gute Entscheidung! Zum Glück habe ich nachgeschaut, der Forscher ist nämlich da!", e: ["f306"] },
		{ id: "f305b", text: "Man sagt ja es gibt keine dummen Ideen aber diese hat mich gerade fast mein Leben gekostet! Benny konnte mich gerade noch zurückhalten, der Forscher ist nämlich da drin.", e: ["f306"] },
		{ id: "f306", text: "Er darf mich auf keinen Fall erwischen! Ich möchte nicht im Käfig bei den anderen Feen landen!", e: ["u307a", "u307b"], typing: 5.0 },
		{ id: "u307a", text: "Dann geh nachhause.", e: ["f308"] },
		{ id: "u307b", text: "Hast du einen Plan?", e: ["f314"] },
		{ id: "f308", text: "Ich soll aufgeben?", e: ["f309"] },
		{ id: "f309", text: "Sicher nicht. Ich schaffe das schon irgendwie. Nur wie?", e: ["u310a", "u310b"], typing: 3.0 },
		{ id: "u310a", text: "Benny kann fliegen.", e: ["f311a"] },
		{ id: "u310b", text: "Geh du.", e: ["f311b"] },
		{ id: "f311a", text: "Aber er sieht ja nichts, wie soll er da ungesehen zum Käfig kommen?", e: ["u312a", "u312b"] },
		{ id: "f311b", text: "Ja, das muss schon ich tun.", e: ["f314"] },
		{ id: "u312a", text: "Er ist eine Biene.", e: ["f313"] },
		{ id: "u312b", text: "Dann geh du.", e: ["f314"] },
		{ id: "f313", text: "Ja aber Menschen lassen Bienen auch nicht gerne in ihren Räumen herumfliegen. Ich glaube ich muss selbst gehen.", e: ["f314"] },
		{ id: "f314", text: "Oh und weisst du, was mir gerade in den Sinn kommt? Als der Forscher bei uns im Feendorf war, hat er sich vor einem Käfer erschrocken. Vielleicht können wir ja etwas mit einem Käfer machen?", e: ["u315a", "u315b"], typing: 5.0 },
		{ id: "u315a", text: "Siehst du einen Käfer?", e: ["f316a"] },
		{ id: "u315b", text: "Du siehst aus wie ein Käfer.", e: ["f316b"] },
		{ id: "f316a", text: "Nein.", e: ["f320a"] },
		{ id: "f316b", text: "Ehhhm danke?", e: ["u317a", "u317b"] },
		{ id: "u317a", text: "Er denkt sicher du bist einer.", e: ["f318a"] },
		{ id: "u317b", text: "Tut mir leid.", e: ["f318b"] },
		{ id: "f318a", text: "Ohhh du hast recht, das könnte klappen!", e: ["u319a", "u319b"] },
		{ id: "f318b", text: "Hm okay. Hier liegt ein Stein. Soll ich ihn werfen und hoffen, dass er den Forscher ablenkt?", e: ["u319c", "u319d"] },
		{ id: "u319a", text: "Nein", e: ["f320a"] },
		{ id: "u319b", text: "Ja", e: ["f340"] },
		{ id: "u319c", text: "Ja", e: ["f325"] },
		{ id: "u319d", text: "Nein", e: ["f320b"] },
		{ id: "f320a", text: "Hier liegt ein Stein, vielleicht kann er mir helfen.", e: ["u321a", "u321b"] },
		{ id: "f320b", text: "Dann muss ich wohl selber auf ihn drauf springen…", e: ["f340"] },
		{ id: "u321a", text: "Gute Idee!", e: ["f322a"] },
		{ id: "u321b", text: "Ich denke nicht.", e: ["f322b"] },
		{ id: "f322a", text: "Soll ich ihn werfen?", e: ["u323a", "u323b"] },
		{ id: "f322b", text: "Was dann? Soll ich selber auf ihn drauf springen?", e: ["u323c", "u323d"] },
		{ id: "u323a", text: "Ja", e: ["f325"] },
		{ id: "u323b", text: "Nein", e: ["f324"] },
		{ id: "u323c", text: "Ja", e: ["f340"] },
		{ id: "u323d", text: "Stein", e: ["f325"] },
		{ id: "f324", text: "Dann muss ich wohl selber auf ihn drauf springen…", e: ["f340"] },
		//Stein:
		{ id: "f325", text: "Okay, ich werde den Stein auf die andere Seite der Forschungsstation werfen und in der Zeit, in der der Forscher abgelenkt ist, werde ich zum Käfig rennen und die Feen befreien.", e: ["u326a", "u326b"], typing: 3.0 },
		{ id: "u326a", text: "Gute Idee", e: ["f328"] },
		{ id: "u326b", text: "Kannst du so weit werfen?", e: ["f327"] },
		{ id: "f327", text: "Ich weiss es nicht, das muss ich wohl ausprobieren.", e: ["f328"] },
		{ id: "f328", text: "Okay, ich werfe ihn. Und sobald ich ihn geworfen habe, werde ich hineingehen und zu den Feen rennen.", e: ["f329"], typing: 4.0 },
		{ id: "f329", text: "Vergiss nicht, dass du das auch über die Überwachungskamera beobachten kannst.", e: ["f330"], typing: 3.0 },
		{ id: "f330", text: "Ich schreib dir, wenn ich zurück bin!", e: ["u331a", "u331b"], typing: 3.0 },
		{ id: "u331a", text: "Okay", e: [""] }, //special
		{ id: "u331b", text: "Viel Glück!", e: [""] },//special
		{ id: "f332", text: "Jetzt habe ich gerade nochmals Glück gehabt!", e: ["u333a", "u333b"] },
		{ id: "u333a", text: "Hast du sie befreit?", e: ["f334"] },
		{ id: "u333b", text: "Was ist passiert?", e: ["f335"] },
		{ id: "f334", text: "Nein, ich kam nicht so weit.", e: ["f335"] },
		{ id: "f335", text: "Ich konnte den Stein tatsächlich auf die andere Seite des Raumes werfen, aber der Forscher drehte sich nur kurz um und hat dann einfach weitergearbeitet.", e: ["f336"], typing: 4.0 },
		{ id: "f336", text: "Ich konnte gerade noch zurück nach draussen schlüpfen, bevor er mich entdecken konnte…", e: ["u337a", "u337b"], typing: 4.0 },
		{ id: "u337a", text: "Und jetzt?", e: ["f339"] },
		{ id: "u337b", text: "Geh nachhause", e: ["f338"] },
		{ id: "f338", text: "Hast du es immer noch nicht gelernt? Ich gebe nicht auf! Nie!", e: ["f339"] },
		{ id: "f339", text: "Ich muss wohl selber auf ihn drauf springen.", e: ["f340"] },
		//Käfer
		{ id: "f340", text: "Ich glaube diese Idee ist die einzige, die funktioniert.", e: ["f341"], typing: 4.0 },
		{ id: "f341", text: "Und ich sehe ja tatsächlich ein bisschen aus wie ein dicker Käfer. Hoffen wir einfach, dass der Forscher nicht zu genau hinsieht…", e: ["u342a", "u342b"], typing: 4.5 },
		{ id: "u342a", text: "Das geht schon.", e: ["f343.5"] },
		{ id: "u342b", text: "Kannst du so weit springen?", e: ["f343"] },
		{ id: "f343", text: "Ich denke schon. Der Forscher arbeitet gleich neben dem Fenster.", e: ["f343.5"] },
		{ id: "f343.5", text: "Ich werde auf seinen Arm springen und wie der Käfer bei uns im Feenwald darauf herumkrabbeln.", e: ["u344a", "u344b"], typing: 3.0 },
		{ id: "u344a", text: "Okay", e: ["f346"] },
		{ id: "u344b", text: "Wie kommst du zum Käfig?", e: ["f345"] },
		{ id: "f345", text: "Das weiss ich auch noch nicht. Ich werde einfach improvisieren.", e: ["f346"] },
		{ id: "f346", text: "Ich kann dir keine Nachrichten mehr senden, sobald ich im Labor bin. Dann muss alles schnell gehen. Möchtest du, dass ich Benny meinen Smartknopf gebe, damit er dir erzählen kann, was er hört?", e: ["u347a", "u347b"], typing: 4.0 },
		{ id: "u347a", text: "Ja", e: ["f348a"] },
		{ id: "u347b", text: "Nein", e: ["f348b"] },
		{ id: "f348a", text: "Okay, ich gebe ihn ihm und gehe. Bis nachher!", e: [""] }, //special
		{ id: "f348b", text: "Okay, wenn du wissen möchtest, was passiert, musst du eben auf dem Video nachsehen. Ich glaube du siehst nicht wirklich ins Labor hinein, aber du wirst immerhin sehen, was draussen vor sich geht.", e: ["f349"] },
		{ id: "f349", text: "Okay, ich gehe dann mal!", e: ["u351a", "u352b"], typing: 4.0 },
		{ id: "f350", text: "Hallo, hier ist Benny!", e: ["u353a", "u353b"] },
		{ id: "u351a", text: "Viel Glück!", e: [""] }, //special
		{ id: "u352b", text: "Bis nachher!", e: [""] }, //special
		{ id: "u353a", text: "Hallo Benny!", e: ["f355"] },
		{ id: "u353b", text: "Wie kannst du schreiben? Du bist blind?", e: ["f354"] },
		{ id: "f354", text: "Der Knopf funktioniert über Spracheingabe. Ich kann ganz normal sprechen und der Knopf nimmt es auf und sendet dir die Nachricht als Text. Und deine Nachrichten werden mir auch vorgelesen.", e: ["f355"] },
		{ id: "f355", text: "Okay, Freddy ist gesprungen.", e: ["f356", "r"], typing: 4.0 },
		{ id: "f356", text: "Ich glaube, er hat den Forscher erwischt! Ich höre ihn kreischen!  ", e: ["f357"], typing: 3.0 },
		{ id: "f357", text: "Jetzt höre ich Getrampel. Und ein metallisches doiiiing. Was das wohl war?", e: ["f358"], typing: 2.0 },
		{ id: "f358", text: "Die Schritte des Forschers werden leiser, ich glaube, er hat den Raum verlassen.", e: ["u359a", "u359b"] },
		{ id: "u359a", text: "Und Freddy?", e: ["f360"] },
		{ id: "u359b", text: "Was hörst du jetzt?", e: ["f360"] },
		{ id: "f360", text: "Pssst! So höre ich nichts! Ich höre ein Schaben und das tuscheln der Feen. Sie wirken ganz aufgeregt!", e: ["f361"] },
		{ id: "f361", text: "Jetzt höre ich ein leises quietschen und Flügelschlagen.  ", e: ["f362"], typing: 3.0 },
		{ id: "f362", text: "Ohhh, jetzt höre ich sie laut und deutlich! Die Feen fliegen an mir vorbei! Freddy hat es geschafft!", e: ["f363"], typing: 4.0 },
		{ id: "f363", text: "Du solltest die Feen nun auf dem Video sehen können, falls dich das interessiert.", e: ["u364a", "u364b"], typing: 3.0 },
		{ id: "u364a", text: "Ich schau nach!", e: ["f365a"] },
		{ id: "u364b", text: "Und wo ist Freddy?", e: ["f365b"] },
		{ id: "f365a", text: "Super!", e: [""] }, //special
		{ id: "f365b", text: "Moment…", e: ["f366"] },
		{ id: "f366", text: "Ah, jetzt höre ich ihn, er klettert gerade wieder zum Fenster hoch!", e: ["f367"] },
		{ id: "f367", text: "Er ist zurück! Ich gebe ihm den Knopf wieder! War schön mit dir zu sprechen!", e: ["f368"], typing: 4.0 },
		{ id: "f368", text: "Ich bin wieder da. Und ich habe es geschafft! Soll ich dir davon erzählen?", e: ["u369a", "u369b", "m"], typing: 4.0 },
		{ id: "u369a", text: "Ja", e: ["f373"] },
		{ id: "u369b", text: "Nein", e: ["f370"] },
		{ id: "f370", text: "Sicher?", e: ["u371a", "u371b"] },
		{ id: "u371a", text: "Nein", e: ["f372a"] },
		{ id: "u371b", text: "Ja", e: ["f372b"] },
		{ id: "f372a", text: "Okay, dann erzähle ich es dir.", e: ["f373"] },
		{ id: "f372b", text: "Dann erzähle ich es eben nicht. Aber der Plan hat genau so funktioniert, wie wir das wollten!", e: ["f378"] },
		{ id: "f373", text: "Ich bin wie geplant auf den Arm des Forschers gesprungen. Und er hat wieder genau so reagiert wie beim letzten Mal. Er hat gekreischt und gezappelt und hat mich mit seinem herumfuchtelnden Arm direkt gegen den Käfig geschleudert.", e: ["f374"], typing: 5.0 },
		{ id: "f374", text: "Dann ist er davongerannt. Und ich konnte den Käfig öffnen.", e: ["u375a", "u375b"], typing: 4.0 },
		{ id: "u375a", text: "Wie?", e: ["f376a"] },
		{ id: "u375b", text: "Erzähl weiter.", e: ["f376a"] },
		{ id: "f376a", text: "Mit einer Büroklammer, die danebenlag.", e: ["f377"] },
		{ id: "f377", text: "Dann sind alle Feen an mir vorbeigeflogen und geflüchtet.", e: ["f378"], typing: 3.0 },
		{ id: "f378", text: "Ich habe es geschafft!", e: ["u379a", "u379b"] },
		{ id: "u379a", text: "Und jetzt?", e: ["f381"] },
		{ id: "u379b", text: "Gratuliere!", e: ["f380"] },
		{ id: "f380", text: "Danke!", e: ["f381"] },
		{ id: "f381", text: "Die Feen haben sich sehr gefreut, mich zu sehen und sich entschuldigt dafür, dass sie so gemein zu mir waren.", e: ["u382a", "u382b"] },
		{ id: "u382a", text: "Seid ihr jetzt Freunde?", e: ["f383a"] },
		{ id: "u382b", text: "Hinterhältig…", e: ["f383b"] },
		{ id: "f383a", text: "Ich hoffe schon irgendwie? Oder zumindest, dass sie jetzt nicht mehr gemein zu mir sein werden.", e: ["f385"] },
		{ id: "f383b", text: "Meinst du, dass sie das nur gesagt haben, weil sie etwas von mir wollten?", e: ["f384"] },
		{ id: "f384", text: "Weisst du, das spielt für mich auch gar keine so grosse Rolle.", e: ["f385"], typing: 4.0 },
		{ id: "f385", text: "Ich werde einmal sehen, wie es sein wird, wenn wir zurück in unserem Wald sind. Vielleicht ist dann alles wieder wie vorher, vielleicht aber auch nicht. Mal sehen.", e: ["f386"], typing: 5.0 },
		{ id: "f386", text: "Aber ich werde vorsichtig sein. Falsche Freunde brauche ich nicht. Und ich habe jetzt ja Benny!", e: ["u387a", "u387b"], typing: 4.0 },
		{ id: "u387a", text: "Also gehst du zurück?", e: ["f388"] },
		{ id: "u387b", text: "Baust du deine Hütte wieder auf?", e: ["f388"] },
		{ id: "f388", text: "Ich denke schon.", e: ["f389"] },
		{ id: "f389", text: "Und ich werde Benny fragen, ob er mitkommen möchte. Es hat ja noch Platz für eine zweite Hütte.", e: ["f390"] },
		{ id: "f390", text: "Benny sagt ja! Er kommt mit! Wir werden Nachbarn sein!", e: ["u391a", "u391b"] },
		{ id: "u391a", text: "So toll!", e: ["f392"] },
		{ id: "u391b", text: "Dann macht euch auf den Weg.", e: ["f392"] },
		{ id: "f392", text: "Vielen Dank für deine Hilfe, ohne dich hätte ich das alles nie geschafft!", e: ["f393"] },
		{ id: "f393", text: "Wenn du Mal im Feenwald bist, musst du uns unbedingt besuchen kommen!", e: ["u394a", "u394b"], typing: 4.0 },
		{ id: "u394a", text: "Gern geschehen!", e: ["f395"] },
		{ id: "u394b", text: "Das mach ich!", e: ["f395"] },
		{ id: "f395", text: "Bis bald!", e: ["c"] }, //special

		//temp testing
		{ id: "f400", text: "ä ö ü", e: [] }, //special
		{ id: "f401", text: "ä ö ü", e: [] }, //special
		{ id: "f402", text: "ä ö ü", e: [] }, //special
];